
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleSkillConfig : Luban.BeanBase
{
    public BattleSkillConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["count"].IsNumber) { throw new SerializationException(); }  Count = _buf["count"]; }
        { var __json0 = _buf["list"]; if(!__json0.IsArray) { throw new SerializationException(); } List = new System.Collections.Generic.List<string>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { string __v0;  { if(!__e0.IsString) { throw new SerializationException(); }  __v0 = __e0; }  List.Add(__v0); }   }
        { var __json0 = _buf["NeedKey"]; if(!__json0.IsArray) { throw new SerializationException(); } NeedKey = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NeedKey.Add(__v0); }   }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { if(!_buf["DoDesitionMoment"].IsNumber) { throw new SerializationException(); }  DoDesitionMoment = _buf["DoDesitionMoment"]; }
        { if(!_buf["StartActionWheelMoment"].IsNumber) { throw new SerializationException(); }  StartActionWheelMoment = _buf["StartActionWheelMoment"]; }
        { if(!_buf["AsTargetActionMoment"].IsNumber) { throw new SerializationException(); }  AsTargetActionMoment = _buf["AsTargetActionMoment"]; }
        { if(!_buf["ReleaseSkillActionMoment"].IsNumber) { throw new SerializationException(); }  ReleaseSkillActionMoment = _buf["ReleaseSkillActionMoment"]; }
        { if(!_buf["BeforeClashMoment"].IsNumber) { throw new SerializationException(); }  BeforeClashMoment = _buf["BeforeClashMoment"]; }
        { if(!_buf["UnderHitMoment"].IsNumber) { throw new SerializationException(); }  UnderHitMoment = _buf["UnderHitMoment"]; }
        { if(!_buf["AfterClashMoment"].IsNumber) { throw new SerializationException(); }  AfterClashMoment = _buf["AfterClashMoment"]; }
        { if(!_buf["AfterActionMoment"].IsNumber) { throw new SerializationException(); }  AfterActionMoment = _buf["AfterActionMoment"]; }
    }

    public static BattleSkillConfig DeserializeBattleSkillConfig(JSONNode _buf)
    {
        return new BattleSkillConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 个数
    /// </summary>
    public readonly int Count;
    /// <summary>
    /// null
    /// </summary>
    public readonly System.Collections.Generic.List<string> List;
    /// <summary>
    /// 技能需要的键
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeedKey;
    /// <summary>
    /// 技能威力
    /// </summary>
    public readonly int Damage;
    /// <summary>
    /// 行动决定后扳机
    /// </summary>
    public readonly int DoDesitionMoment;
    /// <summary>
    /// 息开始扳机
    /// </summary>
    public readonly int StartActionWheelMoment;
    /// <summary>
    /// 被作为目标时扳机
    /// </summary>
    public readonly int AsTargetActionMoment;
    /// <summary>
    /// 释放成功后扳机
    /// </summary>
    public readonly int ReleaseSkillActionMoment;
    /// <summary>
    /// 交锋前扳机
    /// </summary>
    public readonly int BeforeClashMoment;
    /// <summary>
    /// 命中后扳机
    /// </summary>
    public readonly int UnderHitMoment;
    /// <summary>
    /// 交锋后扳机
    /// </summary>
    public readonly int AfterClashMoment;
    /// <summary>
    /// 行动后
    /// </summary>
    public readonly int AfterActionMoment;
   
    public const int __ID__ = -905515781;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "count:" + Count + ","
        + "list:" + Luban.StringUtil.CollectionToString(List) + ","
        + "NeedKey:" + Luban.StringUtil.CollectionToString(NeedKey) + ","
        + "Damage:" + Damage + ","
        + "DoDesitionMoment:" + DoDesitionMoment + ","
        + "StartActionWheelMoment:" + StartActionWheelMoment + ","
        + "AsTargetActionMoment:" + AsTargetActionMoment + ","
        + "ReleaseSkillActionMoment:" + ReleaseSkillActionMoment + ","
        + "BeforeClashMoment:" + BeforeClashMoment + ","
        + "UnderHitMoment:" + UnderHitMoment + ","
        + "AfterClashMoment:" + AfterClashMoment + ","
        + "AfterActionMoment:" + AfterActionMoment + ","
        + "}";
    }
}

}

