
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleMomentType
    {
        /// <summary>
        /// 战斗开始
        /// </summary>
        BattleStart = 1,
        /// <summary>
        /// 回合开始
        /// </summary>
        RoundStart = 2,
        /// <summary>
        /// 决定后
        /// </summary>
        DoDesitionAction = 3,
        /// <summary>
        /// 行动前
        /// </summary>
        BeforeAction = 4,
        /// <summary>
        /// 受到行动前
        /// </summary>
        BeforeUnderAction = 5,
        /// <summary>
        /// 交锋前
        /// </summary>
        BeforeClash = 6,
        /// <summary>
        /// 交锋后
        /// </summary>
        AfterClash = 7,
        /// <summary>
        /// 释放成功
        /// </summary>
        ReleaseSkillAction = 8,
        /// <summary>
        /// 受到行动后
        /// </summary>
        AfterUnderAction = 9,
        /// <summary>
        /// 行动后
        /// </summary>
        AfterAction = 10,
        /// <summary>
        /// 回合结束
        /// </summary>
        RoundEnd = 11,
        /// <summary>
        /// buff添加层数
        /// </summary>
        BuffAddLayer = 12,
        /// <summary>
        /// buff减少层数
        /// </summary>
        BuffReduceLayer = 13,
        /// <summary>
        /// 技能结束
        /// </summary>
        SkillEnd = 14,
        /// <summary>
        /// buff移除
        /// </summary>
        BuffRemove = 15,
        /// <summary>
        /// 自己息开始
        /// </summary>
        ActionWheelStart = 16,
        /// <summary>
        /// 计算息
        /// </summary>
        CalculateActionWheel = 17,
        /// <summary>
        /// buff开始
        /// </summary>
        BuffStart = 18,
        /// <summary>
        /// 息结束
        /// </summary>
        ActionWheelEnd = 19,
        /// <summary>
        /// 每息开始
        /// </summary>
        EveryActionWheelStart = 20,
    }

} 

