
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleMomentConditionConfig : Luban.BeanBase
{
    public BattleMomentConditionConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["ConditionName"].IsString) { throw new SerializationException(); }  ConditionName = _buf["ConditionName"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static BattleMomentConditionConfig DeserializeBattleMomentConditionConfig(JSONNode _buf)
    {
        return new BattleMomentConditionConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 处理器代码名称
    /// </summary>
    public readonly string ConditionName;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = -360293339;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ConditionName:" + ConditionName + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

