
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleSource
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// Buff效果
        /// </summary>
        Buff = 1,
        /// <summary>
        /// 心法
        /// </summary>
        HeartMethod = 2,
        /// <summary>
        /// 技能
        /// </summary>
        Skill = 3,
        /// <summary>
        /// 宝具
        /// </summary>
        Treasure = 4,
        /// <summary>
        /// 自然
        /// </summary>
        Natural = 5,
    }

} 

