
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleBuffConfig : Luban.BeanBase
{
    public BattleBuffConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["Script"].IsString) { throw new SerializationException(); }  Script = _buf["Script"]; }
        { if(!_buf["BuffType"].IsNumber) { throw new SerializationException(); }  BuffType = _buf["BuffType"]; }
        { if(!_buf["OverlayType"].IsNumber) { throw new SerializationException(); }  OverlayType = _buf["OverlayType"]; }
        { if(!_buf["Limit"].IsNumber) { throw new SerializationException(); }  Limit = _buf["Limit"]; }
        { var __json0 = _buf["Mechanism"]; if(!__json0.IsArray) { throw new SerializationException(); } Mechanism = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Mechanism.Add(__v0); }   }
        { var __json0 = _buf["MechanismParam"]; if(!__json0.IsArray) { throw new SerializationException(); } MechanismParam = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MechanismParam.Add(__v0); }   }
        { var __json0 = _buf["ParamEx"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamEx = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ParamEx.Add(__v0); }   }
        { var __json0 = _buf["BuffLevelReduceMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffLevelReduceMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffLevelReduceMoment.Add(__v0); }   }
        { if(!_buf["BeStatusPersists"].IsNumber) { throw new SerializationException(); }  BeStatusPersists = _buf["BeStatusPersists"]; }
    }

    public static BattleBuffConfig DeserializeBattleBuffConfig(JSONNode _buf)
    {
        return new BattleBuffConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// buff脚本
    /// </summary>
    public readonly string Script;
    /// <summary>
    /// Buff类型
    /// </summary>
    public readonly int BuffType;
    /// <summary>
    /// buff叠加类型
    /// </summary>
    public readonly int OverlayType;
    /// <summary>
    /// 限制层数
    /// </summary>
    public readonly int Limit;
    /// <summary>
    /// 机制
    /// </summary>
    public readonly System.Collections.Generic.List<int> Mechanism;
    /// <summary>
    /// 机制参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> MechanismParam;
    /// <summary>
    /// 额外参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> ParamEx;
    /// <summary>
    /// Buff层数减少扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffLevelReduceMoment;
    /// <summary>
    /// 是否受状态续存的影响
    /// </summary>
    public readonly int BeStatusPersists;
   
    public const int __ID__ = 1259790445;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "Script:" + Script + ","
        + "BuffType:" + BuffType + ","
        + "OverlayType:" + OverlayType + ","
        + "Limit:" + Limit + ","
        + "Mechanism:" + Luban.StringUtil.CollectionToString(Mechanism) + ","
        + "MechanismParam:" + Luban.StringUtil.CollectionToString(MechanismParam) + ","
        + "ParamEx:" + Luban.StringUtil.CollectionToString(ParamEx) + ","
        + "BuffLevelReduceMoment:" + Luban.StringUtil.CollectionToString(BuffLevelReduceMoment) + ","
        + "BeStatusPersists:" + BeStatusPersists + ","
        + "}";
    }
}

}

