
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleSkillConfig : Luban.BeanBase
{
    public BattleSkillConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["AniName"].IsString) { throw new SerializationException(); }  AniName = _buf["AniName"]; }
        { if(!_buf["SkillType"].IsNumber) { throw new SerializationException(); }  SkillType = _buf["SkillType"]; }
        { if(!_buf["DamageType"].IsNumber) { throw new SerializationException(); }  DamageType = _buf["DamageType"]; }
        { var __json0 = _buf["NeedKey"]; if(!__json0.IsArray) { throw new SerializationException(); } NeedKey = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NeedKey.Add(__v0); }   }
        { if(!_buf["GangQiCost"].IsNumber) { throw new SerializationException(); }  GangQiCost = _buf["GangQiCost"]; }
        { if(!_buf["XuanQiCost"].IsNumber) { throw new SerializationException(); }  XuanQiCost = _buf["XuanQiCost"]; }
        { if(!_buf["Damage"].IsNumber) { throw new SerializationException(); }  Damage = _buf["Damage"]; }
        { var __json0 = _buf["DoDesitionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } DoDesitionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DoDesitionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeActionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeUnderActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeUnderActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeUnderActionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeClashMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeClashMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeClashMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterClashMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterClashMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterClashMoment.Add(__v0); }   }
        { var __json0 = _buf["ReleaseSkillActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } ReleaseSkillActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ReleaseSkillActionMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterUnderActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterUnderActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterUnderActionMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterActionMoment.Add(__v0); }   }
        { var __json0 = _buf["RoundEndMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } RoundEndMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RoundEndMoment.Add(__v0); }   }
        { var __json0 = _buf["SkillEndMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillEndMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillEndMoment.Add(__v0); }   }
    }

    public static BattleSkillConfig DeserializeBattleSkillConfig(JSONNode _buf)
    {
        return new BattleSkillConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 动画名称
    /// </summary>
    public readonly string AniName;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly int SkillType;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly int DamageType;
    /// <summary>
    /// 技能需要的键
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeedKey;
    /// <summary>
    /// 刚炁消耗
    /// </summary>
    public readonly float GangQiCost;
    /// <summary>
    /// 玄炁消耗
    /// </summary>
    public readonly float XuanQiCost;
    /// <summary>
    /// 技能威力
    /// </summary>
    public readonly float Damage;
    /// <summary>
    /// 行动决定后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> DoDesitionMoment;
    /// <summary>
    /// 行动前
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeActionMoment;
    /// <summary>
    /// 受到行动前调用
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeUnderActionMoment;
    /// <summary>
    /// 交锋前扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeClashMoment;
    /// <summary>
    /// 交锋后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterClashMoment;
    /// <summary>
    /// 释放成功后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> ReleaseSkillActionMoment;
    /// <summary>
    /// 受到行动后调用扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterUnderActionMoment;
    /// <summary>
    /// 行动后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterActionMoment;
    /// <summary>
    /// 回合结束扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> RoundEndMoment;
    /// <summary>
    /// 技能结束扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillEndMoment;
   
    public const int __ID__ = -905515781;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "AniName:" + AniName + ","
        + "SkillType:" + SkillType + ","
        + "DamageType:" + DamageType + ","
        + "NeedKey:" + Luban.StringUtil.CollectionToString(NeedKey) + ","
        + "GangQiCost:" + GangQiCost + ","
        + "XuanQiCost:" + XuanQiCost + ","
        + "Damage:" + Damage + ","
        + "DoDesitionMoment:" + Luban.StringUtil.CollectionToString(DoDesitionMoment) + ","
        + "BeforeActionMoment:" + Luban.StringUtil.CollectionToString(BeforeActionMoment) + ","
        + "BeforeUnderActionMoment:" + Luban.StringUtil.CollectionToString(BeforeUnderActionMoment) + ","
        + "BeforeClashMoment:" + Luban.StringUtil.CollectionToString(BeforeClashMoment) + ","
        + "AfterClashMoment:" + Luban.StringUtil.CollectionToString(AfterClashMoment) + ","
        + "ReleaseSkillActionMoment:" + Luban.StringUtil.CollectionToString(ReleaseSkillActionMoment) + ","
        + "AfterUnderActionMoment:" + Luban.StringUtil.CollectionToString(AfterUnderActionMoment) + ","
        + "AfterActionMoment:" + Luban.StringUtil.CollectionToString(AfterActionMoment) + ","
        + "RoundEndMoment:" + Luban.StringUtil.CollectionToString(RoundEndMoment) + ","
        + "SkillEndMoment:" + Luban.StringUtil.CollectionToString(SkillEndMoment) + ","
        + "}";
    }
}

}

