
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleMomentConfig : Luban.BeanBase
{
    public BattleMomentConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { var __json0 = _buf["ConditionID"]; if(!__json0.IsArray) { throw new SerializationException(); } ConditionID = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ConditionID.Add(__v0); }   }
        { if(!_buf["ConditionReleation"].IsNumber) { throw new SerializationException(); }  ConditionReleation = _buf["ConditionReleation"]; }
        { var __json0 = _buf["SuccessMomentEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } SuccessMomentEffect = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SuccessMomentEffect.Add(__v0); }   }
        { var __json0 = _buf["FailMomentEffect"]; if(!__json0.IsArray) { throw new SerializationException(); } FailMomentEffect = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  FailMomentEffect.Add(__v0); }   }
    }

    public static BattleMomentConfig DeserializeBattleMomentConfig(JSONNode _buf)
    {
        return new BattleMomentConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 条件处理器ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> ConditionID;
    /// <summary>
    /// 条件处理关系符号（0或1与）
    /// </summary>
    public readonly int ConditionReleation;
    /// <summary>
    /// 成功ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> SuccessMomentEffect;
    /// <summary>
    /// 失败ID
    /// </summary>
    public readonly System.Collections.Generic.List<int> FailMomentEffect;
   
    public const int __ID__ = 72777306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ConditionID:" + Luban.StringUtil.CollectionToString(ConditionID) + ","
        + "ConditionReleation:" + ConditionReleation + ","
        + "SuccessMomentEffect:" + Luban.StringUtil.CollectionToString(SuccessMomentEffect) + ","
        + "FailMomentEffect:" + Luban.StringUtil.CollectionToString(FailMomentEffect) + ","
        + "}";
    }
}

}

