
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleMomentEffectConfig : Luban.BeanBase
{
    public BattleMomentEffectConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["EffectName"].IsString) { throw new SerializationException(); }  EffectName = _buf["EffectName"]; }
        { var __json0 = _buf["ParamList"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamList = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ParamList.Add(__v0); }   }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
    }

    public static BattleMomentEffectConfig DeserializeBattleMomentEffectConfig(JSONNode _buf)
    {
        return new BattleMomentEffectConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 效果代码名称
    /// </summary>
    public readonly string EffectName;
    /// <summary>
    /// 参数表
    /// </summary>
    public readonly System.Collections.Generic.List<float> ParamList;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
   
    public const int __ID__ = 734544203;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "EffectName:" + EffectName + ","
        + "ParamList:" + Luban.StringUtil.CollectionToString(ParamList) + ","
        + "desc:" + Desc + ","
        + "}";
    }
}

}

