
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleClashType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 单方面行动
        /// </summary>
        SingleAction = 1,
        /// <summary>
        /// 单向交锋
        /// </summary>
        SingleClash = 2,
        /// <summary>
        /// 双向交锋
        /// </summary>
        DoubleClash = 3,
    }

} 

