
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleUnitTransformState
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 兽
        /// </summary>
        Shou = 1,
        /// <summary>
        /// 禽
        /// </summary>
        Qin = 2,
        /// <summary>
        /// 祖
        /// </summary>
        Zu = 3,
    }

} 

