
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleMomentConfig : Luban.BeanBase
{
    public BattleMomentConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["ConditionID"].IsNumber) { throw new SerializationException(); }  ConditionID = _buf["ConditionID"]; }
        { if(!_buf["SuccessMomentEffect"].IsNumber) { throw new SerializationException(); }  SuccessMomentEffect = _buf["SuccessMomentEffect"]; }
        { if(!_buf["FailMomentEffect"].IsNumber) { throw new SerializationException(); }  FailMomentEffect = _buf["FailMomentEffect"]; }
    }

    public static BattleMomentConfig DeserializeBattleMomentConfig(JSONNode _buf)
    {
        return new BattleMomentConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 条件处理器ID
    /// </summary>
    public readonly int ConditionID;
    /// <summary>
    /// 成功ID
    /// </summary>
    public readonly int SuccessMomentEffect;
    /// <summary>
    /// 失败ID
    /// </summary>
    public readonly int FailMomentEffect;
   
    public const int __ID__ = 72777306;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "ConditionID:" + ConditionID + ","
        + "SuccessMomentEffect:" + SuccessMomentEffect + ","
        + "FailMomentEffect:" + FailMomentEffect + ","
        + "}";
    }
}

}

