
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleMomentType
    {
        BattleStart = 1,
        RoundStart = 2,
        DoDesitionAction = 3,
        BeforeAction = 4,
        BeforeUnderAction = 5,
        BeforeClash = 6,
        AfterClash = 7,
        ReleaseSkillAction = 8,
        AfterUnderAction = 9,
        AfterAction = 10,
        RoundEnd = 11,
        BuffAdd = 12,
        BuffEnd = 13,
        SkillEnd = 14,
        BuffReduce = 15,
    }

} 

