
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleRenderResourceCostReason
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 破招
        /// </summary>
        BeCounter = 1,
        /// <summary>
        /// 行动中
        /// </summary>
        Action = 2,
        /// <summary>
        /// 交锋
        /// </summary>
        Clash = 3,
        /// <summary>
        /// 技能释放失败
        /// </summary>
        UseSkillFail = 4,
        /// <summary>
        /// 技能释放成功
        /// </summary>
        UseSkillSuccess = 5,
    }

} 

