
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleKeyType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 上键
        /// </summary>
        KeyUp = 1,
        /// <summary>
        /// 下键
        /// </summary>
        KeyDown = 2,
        /// <summary>
        /// 左键
        /// </summary>
        KeyLeft = 3,
        /// <summary>
        /// 右键
        /// </summary>
        KeyRight = 4,
        /// <summary>
        /// 键存储最大值
        /// </summary>
        KeyMax = 21001,
        /// <summary>
        /// 额外键存储值
        /// </summary>
        KeyMaxEx = 21002,
        /// <summary>
        /// 自然恢复键数量
        /// </summary>
        KeyRecoverNatural = 21003,
    }

} 

