
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleBuffConfig : Luban.BeanBase
{
    public BattleBuffConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["Script"].IsString) { throw new SerializationException(); }  Script = _buf["Script"]; }
        { if(!_buf["OverlayType"].IsNumber) { throw new SerializationException(); }  OverlayType = _buf["OverlayType"]; }
        { if(!_buf["Limit"].IsNumber) { throw new SerializationException(); }  Limit = _buf["Limit"]; }
        { var __json0 = _buf["CheckSkillRelease"]; if(!__json0.IsArray) { throw new SerializationException(); } CheckSkillRelease = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  CheckSkillRelease.Add(__v0); }   }
        { if(!_buf["CheckSkillReleaseRelation"].IsNumber) { throw new SerializationException(); }  CheckSkillReleaseRelation = _buf["CheckSkillReleaseRelation"]; }
        { var __json0 = _buf["BuffLevelReduceMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffLevelReduceMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffLevelReduceMoment.Add(__v0); }   }
        { var __json0 = _buf["BuffAddMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffAddMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffAddMoment.Add(__v0); }   }
        { var __json0 = _buf["BattleStartMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BattleStartMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BattleStartMoment.Add(__v0); }   }
        { var __json0 = _buf["RoundStartMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } RoundStartMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RoundStartMoment.Add(__v0); }   }
        { var __json0 = _buf["DoDesitionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } DoDesitionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DoDesitionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeActionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeUnderActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeUnderActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeUnderActionMoment.Add(__v0); }   }
        { var __json0 = _buf["BeforeClashMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BeforeClashMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeforeClashMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterClashMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterClashMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterClashMoment.Add(__v0); }   }
        { var __json0 = _buf["ReleaseSkillActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } ReleaseSkillActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ReleaseSkillActionMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterUnderActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterUnderActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterUnderActionMoment.Add(__v0); }   }
        { var __json0 = _buf["AfterActionMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } AfterActionMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  AfterActionMoment.Add(__v0); }   }
        { var __json0 = _buf["RoundEndMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } RoundEndMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  RoundEndMoment.Add(__v0); }   }
        { var __json0 = _buf["BuffReduceMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } BuffReduceMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BuffReduceMoment.Add(__v0); }   }
    }

    public static BattleBuffConfig DeserializeBattleBuffConfig(JSONNode _buf)
    {
        return new BattleBuffConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// buff脚本
    /// </summary>
    public readonly string Script;
    /// <summary>
    /// buff叠加类型
    /// </summary>
    public readonly int OverlayType;
    /// <summary>
    /// 限制层数
    /// </summary>
    public readonly int Limit;
    /// <summary>
    /// 判断技能能否释放
    /// </summary>
    public readonly System.Collections.Generic.List<int> CheckSkillRelease;
    /// <summary>
    /// 判断技能能否释放或与（0或，1与）
    /// </summary>
    public readonly int CheckSkillReleaseRelation;
    /// <summary>
    /// Buff层数减少扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffLevelReduceMoment;
    /// <summary>
    /// 添加buff层数时扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffAddMoment;
    /// <summary>
    /// 战斗开始扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BattleStartMoment;
    /// <summary>
    /// 回合开始扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> RoundStartMoment;
    /// <summary>
    /// 行动决定后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> DoDesitionMoment;
    /// <summary>
    /// 行动前
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeActionMoment;
    /// <summary>
    /// 受到行动前调用
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeUnderActionMoment;
    /// <summary>
    /// 交锋前扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeforeClashMoment;
    /// <summary>
    /// 交锋后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterClashMoment;
    /// <summary>
    /// 释放成功后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> ReleaseSkillActionMoment;
    /// <summary>
    /// 受到行动后调用扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterUnderActionMoment;
    /// <summary>
    /// 行动后扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> AfterActionMoment;
    /// <summary>
    /// 回合结束扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> RoundEndMoment;
    /// <summary>
    /// buff减少时扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> BuffReduceMoment;
   
    public const int __ID__ = 1259790445;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "Script:" + Script + ","
        + "OverlayType:" + OverlayType + ","
        + "Limit:" + Limit + ","
        + "CheckSkillRelease:" + Luban.StringUtil.CollectionToString(CheckSkillRelease) + ","
        + "CheckSkillReleaseRelation:" + CheckSkillReleaseRelation + ","
        + "BuffLevelReduceMoment:" + Luban.StringUtil.CollectionToString(BuffLevelReduceMoment) + ","
        + "BuffAddMoment:" + Luban.StringUtil.CollectionToString(BuffAddMoment) + ","
        + "BattleStartMoment:" + Luban.StringUtil.CollectionToString(BattleStartMoment) + ","
        + "RoundStartMoment:" + Luban.StringUtil.CollectionToString(RoundStartMoment) + ","
        + "DoDesitionMoment:" + Luban.StringUtil.CollectionToString(DoDesitionMoment) + ","
        + "BeforeActionMoment:" + Luban.StringUtil.CollectionToString(BeforeActionMoment) + ","
        + "BeforeUnderActionMoment:" + Luban.StringUtil.CollectionToString(BeforeUnderActionMoment) + ","
        + "BeforeClashMoment:" + Luban.StringUtil.CollectionToString(BeforeClashMoment) + ","
        + "AfterClashMoment:" + Luban.StringUtil.CollectionToString(AfterClashMoment) + ","
        + "ReleaseSkillActionMoment:" + Luban.StringUtil.CollectionToString(ReleaseSkillActionMoment) + ","
        + "AfterUnderActionMoment:" + Luban.StringUtil.CollectionToString(AfterUnderActionMoment) + ","
        + "AfterActionMoment:" + Luban.StringUtil.CollectionToString(AfterActionMoment) + ","
        + "RoundEndMoment:" + Luban.StringUtil.CollectionToString(RoundEndMoment) + ","
        + "BuffReduceMoment:" + Luban.StringUtil.CollectionToString(BuffReduceMoment) + ","
        + "}";
    }
}

}

