
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattlePropertyType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 当前体上限
        /// </summary>
        MaxHp = 20001,
        /// <summary>
        /// 基础体上限
        /// </summary>
        BasicMaxHp = 20002,
        /// <summary>
        /// 体上限整数变量
        /// </summary>
        MaxHpInt = 20003,
        /// <summary>
        /// 体上限百分比变量
        /// </summary>
        MaxHpPct = 20004,
        /// <summary>
        /// 体上限外围乘区
        /// </summary>
        AllMaxHpPct = 20005,
        /// <summary>
        /// 当前体
        /// </summary>
        Hp = 20011,
        /// <summary>
        /// 基础体
        /// </summary>
        BasicHp = 20012,
        /// <summary>
        /// 体整数变量
        /// </summary>
        HpInt = 20013,
        /// <summary>
        /// 体百分比变量
        /// </summary>
        HpPct = 20014,
        /// <summary>
        /// 体外围乘区
        /// </summary>
        AllHpPct = 20015,
        /// <summary>
        /// 当前刚炁上限
        /// </summary>
        MaxGangQi = 20021,
        /// <summary>
        /// 基础刚炁上限
        /// </summary>
        BasicMaxGangQi = 20022,
        /// <summary>
        /// 刚炁上限整数变量
        /// </summary>
        MaxGangQiInt = 20023,
        /// <summary>
        /// 刚炁上限百分比变量
        /// </summary>
        MaxGangQiPct = 20024,
        /// <summary>
        /// 刚炁上限外围乘区
        /// </summary>
        AllMaxGangQiPct = 20025,
        /// <summary>
        /// 当前刚炁
        /// </summary>
        GangQi = 20031,
        /// <summary>
        /// 基础刚炁
        /// </summary>
        BasicGangQi = 20032,
        /// <summary>
        /// 刚炁整数变量
        /// </summary>
        GangQiInt = 20033,
        /// <summary>
        /// 刚炁百分比变量
        /// </summary>
        GangQiPct = 20034,
        /// <summary>
        /// 刚炁外围乘区
        /// </summary>
        AllGangQiPct = 20035,
        /// <summary>
        /// 当前玄炁上限
        /// </summary>
        MaxXuanQi = 20041,
        /// <summary>
        /// 基础玄炁上限
        /// </summary>
        BasicMaxXuanQi = 20042,
        /// <summary>
        /// 玄炁上限整数变量
        /// </summary>
        MaxXuanQiInt = 20043,
        /// <summary>
        /// 玄炁上限百分比变量
        /// </summary>
        MaxXuanQiPct = 20044,
        /// <summary>
        /// 玄炁上限外围乘区
        /// </summary>
        AllMaxXuanQiPct = 20045,
        /// <summary>
        /// 当前玄炁
        /// </summary>
        XuanQi = 20051,
        /// <summary>
        /// 基础玄炁
        /// </summary>
        BasicXuanQi = 20052,
        /// <summary>
        /// 玄炁整数变量
        /// </summary>
        XuanQiInt = 20053,
        /// <summary>
        /// 玄炁百分比变量
        /// </summary>
        XuanQiPct = 20054,
        /// <summary>
        /// 玄炁外围乘区
        /// </summary>
        AllXuanQiPct = 20055,
        /// <summary>
        /// 当前力
        /// </summary>
        Power = 20061,
        /// <summary>
        /// 基础力
        /// </summary>
        BasicPower = 20062,
        /// <summary>
        /// 力整数变量
        /// </summary>
        PowerInt = 20063,
        /// <summary>
        /// 力百分比变量
        /// </summary>
        PowerPct = 20064,
        /// <summary>
        /// 力外围乘区
        /// </summary>
        AllPowerPct = 20065,
        /// <summary>
        /// 当前技
        /// </summary>
        Tech = 20071,
        /// <summary>
        /// 基础技
        /// </summary>
        BasicTech = 20072,
        /// <summary>
        /// 技整数变量
        /// </summary>
        TechInt = 20073,
        /// <summary>
        /// 技百分比变量
        /// </summary>
        TechPct = 20074,
        /// <summary>
        /// 技外围乘区
        /// </summary>
        AllTechPct = 20075,
        /// <summary>
        /// 当前速
        /// </summary>
        Speed = 20081,
        /// <summary>
        /// 基础速
        /// </summary>
        BasicSpeed = 20082,
        /// <summary>
        /// 速整数变量
        /// </summary>
        SpeedInt = 20083,
        /// <summary>
        /// 速百分比变量
        /// </summary>
        SpeedPct = 20084,
        /// <summary>
        /// 速外围乘区
        /// </summary>
        AllSpeedPct = 20085,
        /// <summary>
        /// 当前巧
        /// </summary>
        Clever = 20091,
        /// <summary>
        /// 基础巧
        /// </summary>
        BasicClever = 20092,
        /// <summary>
        /// 巧整数变量
        /// </summary>
        CleverInt = 20093,
        /// <summary>
        /// 巧百分比变量
        /// </summary>
        CleverPct = 20094,
        /// <summary>
        /// 巧外围乘区
        /// </summary>
        AllCleverPct = 20095,
        /// <summary>
        /// 当前防
        /// </summary>
        Defend = 20101,
        /// <summary>
        /// 基础防
        /// </summary>
        BasicDefend = 20102,
        /// <summary>
        /// 防整数变量
        /// </summary>
        DefendInt = 20103,
        /// <summary>
        /// 防百分比变量
        /// </summary>
        DefendPct = 20104,
        /// <summary>
        /// 防外围乘区
        /// </summary>
        AllDefendPct = 20105,
        /// <summary>
        /// 当前破
        /// </summary>
        Break = 20111,
        /// <summary>
        /// 基础破
        /// </summary>
        BasicBreak = 20112,
        /// <summary>
        /// 破整数变量
        /// </summary>
        BreakInt = 20113,
        /// <summary>
        /// 破百分比变量
        /// </summary>
        BreakPct = 20114,
        /// <summary>
        /// 破外围乘区
        /// </summary>
        AllBreakPct = 20115,
        /// <summary>
        /// 当前刚炁自然恢复值
        /// </summary>
        GangQiRecNatural = 20121,
        /// <summary>
        /// 刚炁恢复整数变量
        /// </summary>
        GangQiRecInt = 20122,
        /// <summary>
        /// 刚炁恢复百分比变量
        /// </summary>
        GangQiRecPct = 20123,
        /// <summary>
        /// 刚炁恢复外围乘区
        /// </summary>
        AllGangQiRecPct = 20124,
        /// <summary>
        /// 刚炁消耗整数变量
        /// </summary>
        GangQiRedInt = 20125,
        /// <summary>
        /// 刚炁消耗百分比变量
        /// </summary>
        GangQiRedPct = 20126,
        /// <summary>
        /// 刚炁消耗外围乘区
        /// </summary>
        AllGangQiRedPct = 20127,
        /// <summary>
        /// 当前玄炁自然恢复值
        /// </summary>
        XuanQiRecNatural = 20131,
        /// <summary>
        /// 玄炁恢复整数变量
        /// </summary>
        XuanQiRecInt = 20132,
        /// <summary>
        /// 玄炁恢复百分比变量
        /// </summary>
        XuanQiRecPct = 20133,
        /// <summary>
        /// 玄炁恢复外围乘区
        /// </summary>
        AllXuanQiRecPct = 20134,
        /// <summary>
        /// 玄炁消耗整数变量
        /// </summary>
        XuanQiRedInt = 20135,
        /// <summary>
        /// 玄炁消耗百分比变量
        /// </summary>
        XuanQiRedPct = 20136,
        /// <summary>
        /// 玄炁消耗外围乘区
        /// </summary>
        AllXuanQiRedPct = 20137,
        /// <summary>
        /// 伤害减免
        /// </summary>
        DamageReducePct = 22001,
        /// <summary>
        /// 技能伤害百分比变动
        /// </summary>
        SkillDamageRateFloor = 22002,
        /// <summary>
        /// 杀式伤害直接减免
        /// </summary>
        KillingDamageReduceInt = 22003,
        /// <summary>
        /// 因技能获得的刚气该变量偏移值
        /// </summary>
        RecoverGangQiBySkillOffset = 23001,
        /// <summary>
        /// 因技能获得的玄气该变量偏移值
        /// </summary>
        RecoverXuanQiBySkillOffset = 23002,
        /// <summary>
        /// 临时的招式威力
        /// </summary>
        TempSkillDamageAddValue = 23003,
        /// <summary>
        /// 临时的武杀式招式威力
        /// </summary>
        TempPowerSkillDamageAddValue = 23004,
        /// <summary>
        /// 临时的术杀式招式威力
        /// </summary>
        TempArtSkillDamageAddValue = 23005,
    }

} 

