
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleSkillConfig : Luban.BeanBase
{
    public BattleSkillConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["BreakDefendAddRate"].IsNumber) { throw new SerializationException(); }  BreakDefendAddRate = _buf["BreakDefendAddRate"]; }
        { if(!_buf["IsPctCost"].IsNumber) { throw new SerializationException(); }  IsPctCost = _buf["IsPctCost"]; }
        { if(!_buf["IsNeedTarget"].IsNumber) { throw new SerializationException(); }  IsNeedTarget = _buf["IsNeedTarget"]; }
        { if(!_buf["Faction"].IsNumber) { throw new SerializationException(); }  Faction = _buf["Faction"]; }
        { if(!_buf["SkillScript"].IsString) { throw new SerializationException(); }  SkillScript = _buf["SkillScript"]; }
        { if(!_buf["SkillPreUseDataScript"].IsString) { throw new SerializationException(); }  SkillPreUseDataScript = _buf["SkillPreUseDataScript"]; }
        { var __json0 = _buf["ParamEx"]; if(!__json0.IsArray) { throw new SerializationException(); } ParamEx = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ParamEx.Add(__v0); }   }
        { if(!_buf["AniName"].IsString) { throw new SerializationException(); }  AniName = _buf["AniName"]; }
        { if(!_buf["SkillType"].IsNumber) { throw new SerializationException(); }  SkillType = _buf["SkillType"]; }
        { if(!_buf["DamageType"].IsNumber) { throw new SerializationException(); }  DamageType = _buf["DamageType"]; }
        { var __json0 = _buf["NeedKey"]; if(!__json0.IsArray) { throw new SerializationException(); } NeedKey = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NeedKey.Add(__v0); }   }
        { if(!_buf["GangQiCost"].IsNumber) { throw new SerializationException(); }  GangQiCost = _buf["GangQiCost"]; }
        { if(!_buf["XuanQiCost"].IsNumber) { throw new SerializationException(); }  XuanQiCost = _buf["XuanQiCost"]; }
        { if(!_buf["WellyRateBase"].IsNumber) { throw new SerializationException(); }  WellyRateBase = _buf["WellyRateBase"]; }
        { var __json0 = _buf["SkillRemoveMoment"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillRemoveMoment = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillRemoveMoment.Add(__v0); }   }
        { if(!_buf["SkillWellyEffect"].IsNumber) { throw new SerializationException(); }  SkillWellyEffect = _buf["SkillWellyEffect"]; }
        { if(!_buf["SkillArmorPiercing"].IsNumber) { throw new SerializationException(); }  SkillArmorPiercing = _buf["SkillArmorPiercing"]; }
        { if(!_buf["StatusPersists"].IsNumber) { throw new SerializationException(); }  StatusPersists = _buf["StatusPersists"]; }
        { if(!_buf["GainStatusPersists"].IsNumber) { throw new SerializationException(); }  GainStatusPersists = _buf["GainStatusPersists"]; }
        { if(!_buf["NotBeAbnormalBuffEffect"].IsNumber) { throw new SerializationException(); }  NotBeAbnormalBuffEffect = _buf["NotBeAbnormalBuffEffect"]; }
    }

    public static BattleSkillConfig DeserializeBattleSkillConfig(JSONNode _buf)
    {
        return new BattleSkillConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 破防增加比率
    /// </summary>
    public readonly float BreakDefendAddRate;
    /// <summary>
    /// 炁拶
    /// </summary>
    public readonly int IsPctCost;
    /// <summary>
    /// 是否需要目标
    /// </summary>
    public readonly int IsNeedTarget;
    /// <summary>
    /// 派系
    /// </summary>
    public readonly int Faction;
    /// <summary>
    /// 脚本
    /// </summary>
    public readonly string SkillScript;
    /// <summary>
    /// 预先使用数据脚本
    /// </summary>
    public readonly string SkillPreUseDataScript;
    /// <summary>
    /// 特殊参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> ParamEx;
    /// <summary>
    /// 动画名称
    /// </summary>
    public readonly string AniName;
    /// <summary>
    /// 技能类型
    /// </summary>
    public readonly int SkillType;
    /// <summary>
    /// 伤害类型
    /// </summary>
    public readonly int DamageType;
    /// <summary>
    /// 技能需要的键
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeedKey;
    /// <summary>
    /// 刚炁消耗
    /// </summary>
    public readonly float GangQiCost;
    /// <summary>
    /// 玄炁消耗
    /// </summary>
    public readonly float XuanQiCost;
    /// <summary>
    /// 技能威力
    /// </summary>
    public readonly float WellyRateBase;
    /// <summary>
    /// 技能移除扳机
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillRemoveMoment;
    /// <summary>
    /// 威力效果倍数
    /// </summary>
    public readonly float SkillWellyEffect;
    /// <summary>
    /// 破甲
    /// </summary>
    public readonly float SkillArmorPiercing;
    /// <summary>
    /// 是否不影响状态的续存
    /// </summary>
    public readonly int StatusPersists;
    /// <summary>
    /// 是否不影响增益状态的续存
    /// </summary>
    public readonly int GainStatusPersists;
    /// <summary>
    /// 行动期间不受异常状态的影响
    /// </summary>
    public readonly int NotBeAbnormalBuffEffect;
   
    public const int __ID__ = -905515781;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "BreakDefendAddRate:" + BreakDefendAddRate + ","
        + "IsPctCost:" + IsPctCost + ","
        + "IsNeedTarget:" + IsNeedTarget + ","
        + "Faction:" + Faction + ","
        + "SkillScript:" + SkillScript + ","
        + "SkillPreUseDataScript:" + SkillPreUseDataScript + ","
        + "ParamEx:" + Luban.StringUtil.CollectionToString(ParamEx) + ","
        + "AniName:" + AniName + ","
        + "SkillType:" + SkillType + ","
        + "DamageType:" + DamageType + ","
        + "NeedKey:" + Luban.StringUtil.CollectionToString(NeedKey) + ","
        + "GangQiCost:" + GangQiCost + ","
        + "XuanQiCost:" + XuanQiCost + ","
        + "WellyRateBase:" + WellyRateBase + ","
        + "SkillRemoveMoment:" + Luban.StringUtil.CollectionToString(SkillRemoveMoment) + ","
        + "SkillWellyEffect:" + SkillWellyEffect + ","
        + "SkillArmorPiercing:" + SkillArmorPiercing + ","
        + "StatusPersists:" + StatusPersists + ","
        + "GainStatusPersists:" + GainStatusPersists + ","
        + "NotBeAbnormalBuffEffect:" + NotBeAbnormalBuffEffect + ","
        + "}";
    }
}

}

