
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BattleMomentViewType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 战斗开始
        /// </summary>
        BattleStart = 1,
        /// <summary>
        /// 回合开始
        /// </summary>
        RoundStart = 2,
        /// <summary>
        /// 预先行动决定
        /// </summary>
        PreDoDesition = 3,
        /// <summary>
        /// 行动决定
        /// </summary>
        DoDesition = 4,
        /// <summary>
        /// 每一息开始
        /// </summary>
        EveryActionWheelStart = 5,
        /// <summary>
        /// 自己息开始
        /// </summary>
        SelfActionWheelStart = 6,
        /// <summary>
        /// 行动前
        /// </summary>
        BeforeAction = 7,
        /// <summary>
        /// 受到行动前
        /// </summary>
        BeforeUnderAction = 8,
        /// <summary>
        /// 交锋前
        /// </summary>
        BeforeClash = 9,
        /// <summary>
        /// 交锋后
        /// </summary>
        AfterClash = 10,
        /// <summary>
        /// 资源消耗
        /// </summary>
        CostResource = 11,
        /// <summary>
        /// 受到行动后
        /// </summary>
        AfterUnderAction = 12,
        /// <summary>
        /// 行动后（受到行动后，行动后，行动结束）
        /// </summary>
        AfterAction = 13,
    }

} 

