
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class BattleBuffRelationConfig : Luban.BeanBase
{
    public BattleBuffRelationConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["DisposeBuff"]; if(!__json0.IsArray) { throw new SerializationException(); } DisposeBuff = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DisposeBuff.Add(__v0); }   }
        { var __json0 = _buf["MutexBuff"]; if(!__json0.IsArray) { throw new SerializationException(); } MutexBuff = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  MutexBuff.Add(__v0); }   }
    }

    public static BattleBuffRelationConfig DeserializeBattleBuffRelationConfig(JSONNode _buf)
    {
        return new BattleBuffRelationConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 上了这个buff清除里面的buff
    /// </summary>
    public readonly System.Collections.Generic.List<int> DisposeBuff;
    /// <summary>
    /// 有了这个buff不能上
    /// </summary>
    public readonly System.Collections.Generic.List<int> MutexBuff;
   
    public const int __ID__ = -1337655671;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "DisposeBuff:" + Luban.StringUtil.CollectionToString(DisposeBuff) + ","
        + "MutexBuff:" + Luban.StringUtil.CollectionToString(MutexBuff) + ","
        + "}";
    }
}

}

