
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffOverlayType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 触发一下马上结束
        /// </summary>
        Dispose = 1,
        /// <summary>
        /// 覆盖
        /// </summary>
        Cover = 2,
        /// <summary>
        /// 叠加
        /// </summary>
        Overlap = 3,
    }

} 

