
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffReduceType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 减少一层
        /// </summary>
        One = 1,
        /// <summary>
        /// 清空
        /// </summary>
        Clear = 2,
        /// <summary>
        /// 减少最后一次叠加后总计数的1/4
        /// </summary>
        AllCountPct1Q4 = 3,
        /// <summary>
        /// 减少最后一次叠加后总计数的1/3
        /// </summary>
        AllCountPct1Q3 = 4,
        /// <summary>
        /// 减少最后一次叠加后总计数的1/2
        /// </summary>
        AllCountPct1Q2 = 5,
        /// <summary>
        /// 上次行动前获取的全部清空
        /// </summary>
        BeforeLastActionGetAll = 6,
    }

} 

