
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 增益
        /// </summary>
        Gain = 1,
        /// <summary>
        /// 异常
        /// </summary>
        Abnormal = 2,
        /// <summary>
        /// 特殊
        /// </summary>
        Special = 3,
    }

} 

