
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum BuffMechanism
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 无法被施加异常状态
        /// </summary>
        NotBeAddAbnormalBuff = 2,
        /// <summary>
        /// 无法成为被行动的目标
        /// </summary>
        NotBeActionTarget = 3,
        /// <summary>
        /// 封锁上键
        /// </summary>
        LockUpKey = 4,
        /// <summary>
        /// 封锁下键
        /// </summary>
        LockDownKey = 5,
        /// <summary>
        /// 封锁左键
        /// </summary>
        LockLeftKey = 6,
        /// <summary>
        /// 封锁右键
        /// </summary>
        LockRightKey = 7,
        /// <summary>
        /// 回避和盲目
        /// </summary>
        BuffReduceDamage1 = 8,
        /// <summary>
        /// 嘲讽
        /// </summary>
        Mockery = 9,
        /// <summary>
        /// 无法被施加增益状态
        /// </summary>
        NotBeAddGainBuff = 10,
        /// <summary>
        /// 无法生效增益Buff
        /// </summary>
        NotEffectGainBuff = 11,
        /// <summary>
        /// 无法生效异常Buff
        /// </summary>
        NotEffectAbnormalBuff = 12,
        /// <summary>
        /// 无法生效特殊Buff
        /// </summary>
        NotEffectSpecialBuff = 13,
        /// <summary>
        /// 无法直接清除异常状态
        /// </summary>
        NotDirectRemoveAbnormalBuff = 14,
        /// <summary>
        /// 可使用猊煞变派系招式
        /// </summary>
        CanUseNiShaSkill = 15,
    }

} 

