
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ChangeKeyType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 消耗
        /// </summary>
        Cost = 1,
        /// <summary>
        /// 移除
        /// </summary>
        Remove = 2,
        /// <summary>
        /// 转化
        /// </summary>
        Convert = 3,
    }

} 

