
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ChangeKeyReason
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 招式消耗
        /// </summary>
        SkillCost = 1,
        /// <summary>
        /// 自然恢复
        /// </summary>
        NaturalRecover = 2,
        /// <summary>
        /// 初始化
        /// </summary>
        Init = 3,
        /// <summary>
        /// 招式效果
        /// </summary>
        SkillEffect = 4,
        /// <summary>
        /// buff效果
        /// </summary>
        BuffEffect = 5,
        /// <summary>
        /// 物品
        /// </summary>
        Item = 6,
        /// <summary>
        /// 心法效果
        /// </summary>
        HeartMethodEffect = 7,
        /// <summary>
        /// 宝器效果
        /// </summary>
        TreasureEffect = 8,
    }

} 

