
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum ChronoType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 日出
        /// </summary>
        Sunrise = 1,
        /// <summary>
        /// 早晨
        /// </summary>
        Morning = 2,
        /// <summary>
        /// 日落
        /// </summary>
        Sunset = 3,
        /// <summary>
        /// 夜晚
        /// </summary>
        Night = 4,
    }

} 

