
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CommonPoolConfig : Luban.BeanBase
{
    public CommonPoolConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["Pool"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Pool = new CommonPoolData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { CommonPoolData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.CommonPoolData.DeserializeCommonPoolData(__e0);  }  Pool[__index0++] = __v0; }   }
        { if(!_buf["Count"].IsNumber) { throw new SerializationException(); }  Count = _buf["Count"]; }
    }

    public static CommonPoolConfig DeserializeCommonPoolConfig(JSONNode _buf)
    {
        return new CommonPoolConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 池子
    /// </summary>
    public readonly CommonPoolData[] Pool;
    /// <summary>
    /// 抽取数量（0全部抽取）
    /// </summary>
    public readonly int Count;
   
    public const int __ID__ = 2111546089;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in Pool) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Pool:" + Luban.StringUtil.CollectionToString(Pool) + ","
        + "Count:" + Count + ","
        + "}";
    }
}

}

