
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class CommonPoolData : Luban.BeanBase
{
    public CommonPoolData(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Num"].IsNumber) { throw new SerializationException(); }  Num = _buf["Num"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
    }

    public static CommonPoolData DeserializeCommonPoolData(JSONNode _buf)
    {
        return new CommonPoolData(_buf);
    }

    /// <summary>
    /// 池子东西ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 池子东西数量
    /// </summary>
    public readonly int Num;
    public readonly int Weight;
   
    public const int __ID__ = -20132591;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Num:" + Num + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}

}

