
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum DataRelation
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 小于
        /// </summary>
        XiaoYu = 1,
        /// <summary>
        /// 小于等于
        /// </summary>
        XiaoYuDengYu = 2,
        /// <summary>
        /// 等于
        /// </summary>
        DengYu = 3,
        /// <summary>
        /// 大于等于
        /// </summary>
        DaYuDengYu = 4,
        /// <summary>
        /// 大于
        /// </summary>
        DaYu = 5,
    }

} 

