
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DateTypeConfig : Luban.BeanBase
{
    public DateTypeConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["DateTypeDes"].IsString) { throw new SerializationException(); }  DateTypeDes = _buf["DateTypeDes"]; }
    }

    public static DateTypeConfig DeserializeDateTypeConfig(JSONNode _buf)
    {
        return new DateTypeConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 日期类型描述
    /// </summary>
    public readonly string DateTypeDes;
   
    public const int __ID__ = -1615363702;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "DateTypeDes:" + DateTypeDes + ","
        + "}";
    }
}

}

