
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class DateConfig : Luban.BeanBase
{
    public DateConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["SecondID"].IsString) { throw new SerializationException(); }  SecondID = _buf["SecondID"]; }
        { if(!_buf["Year"].IsNumber) { throw new SerializationException(); }  Year = _buf["Year"]; }
        { if(!_buf["Month"].IsNumber) { throw new SerializationException(); }  Month = _buf["Month"]; }
        { if(!_buf["Day"].IsNumber) { throw new SerializationException(); }  Day = _buf["Day"]; }
        { if(!_buf["ShowText"].IsString) { throw new SerializationException(); }  ShowText = _buf["ShowText"]; }
        { if(!_buf["OtherText"].IsString) { throw new SerializationException(); }  OtherText = _buf["OtherText"]; }
        { if(!_buf["Season"].IsNumber) { throw new SerializationException(); }  Season = _buf["Season"]; }
        { var __json0 = _buf["DateType"]; if(!__json0.IsArray) { throw new SerializationException(); } DateType = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  DateType.Add(__v0); }   }
    }

    public static DateConfig DeserializeDateConfig(JSONNode _buf)
    {
        return new DateConfig(_buf);
    }

    /// <summary>
    /// 主键
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 联合主键
    /// </summary>
    public readonly string SecondID;
    /// <summary>
    /// 年
    /// </summary>
    public readonly int Year;
    /// <summary>
    /// 月
    /// </summary>
    public readonly int Month;
    /// <summary>
    /// 日
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string ShowText;
    /// <summary>
    /// 其余显示（农历记日）
    /// </summary>
    public readonly string OtherText;
    /// <summary>
    /// 季候
    /// </summary>
    public readonly int Season;
    /// <summary>
    /// 日期类型标签
    /// </summary>
    public readonly System.Collections.Generic.List<int> DateType;
   
    public const int __ID__ = 2062696624;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SecondID:" + SecondID + ","
        + "Year:" + Year + ","
        + "Month:" + Month + ","
        + "Day:" + Day + ","
        + "ShowText:" + ShowText + ","
        + "OtherText:" + OtherText + ","
        + "Season:" + Season + ","
        + "DateType:" + Luban.StringUtil.CollectionToString(DateType) + ","
        + "}";
    }
}

}

