
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum GetPropertySourceType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 受伤时获取属性
        /// </summary>
        ReceiveSkillDamage = 1,
        /// <summary>
        /// 获取技能显示消耗
        /// </summary>
        GetSkillCostView = 2,
        /// <summary>
        /// 获取技能判断消耗
        /// </summary>
        GetSkillCostCheck = 3,
        /// <summary>
        /// 获取技能真实消耗
        /// </summary>
        GetSkillCostLogic = 4,
    }

} 

