
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class HeroConfig : Luban.BeanBase
{
    public HeroConfig(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["HeroName"].IsString) { throw new SerializationException(); }  HeroName = _buf["HeroName"]; }
        { if(!_buf["HeroFightProperty"].IsNumber) { throw new SerializationException(); }  HeroFightProperty = _buf["HeroFightProperty"]; }
        { var __json0 = _buf["InitItemPool"]; if(!__json0.IsArray) { throw new SerializationException(); } InitItemPool = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  InitItemPool.Add(__v0); }   }
        { if(!_buf["ItemDropPool"].IsNumber) { throw new SerializationException(); }  ItemDropPool = _buf["ItemDropPool"]; }
        { if(!_buf["ExpDrop"].IsNumber) { throw new SerializationException(); }  ExpDrop = _buf["ExpDrop"]; }
        { if(!_buf["HeartMethodPool"].IsNumber) { throw new SerializationException(); }  HeartMethodPool = _buf["HeartMethodPool"]; }
        { if(!_buf["PowerKillingPool"].IsNumber) { throw new SerializationException(); }  PowerKillingPool = _buf["PowerKillingPool"]; }
        { if(!_buf["ArtKillingPool"].IsNumber) { throw new SerializationException(); }  ArtKillingPool = _buf["ArtKillingPool"]; }
        { if(!_buf["TechniqueImperialStylePool"].IsNumber) { throw new SerializationException(); }  TechniqueImperialStylePool = _buf["TechniqueImperialStylePool"]; }
        { if(!_buf["SpellFormulaPool"].IsNumber) { throw new SerializationException(); }  SpellFormulaPool = _buf["SpellFormulaPool"]; }
        { if(!_buf["ExtraSkillPool"].IsNumber) { throw new SerializationException(); }  ExtraSkillPool = _buf["ExtraSkillPool"]; }
        { if(!_buf["BattleLines"].IsNumber) { throw new SerializationException(); }  BattleLines = _buf["BattleLines"]; }
        { if(!_buf["BattleAction"].IsNumber) { throw new SerializationException(); }  BattleAction = _buf["BattleAction"]; }
        { if(!_buf["IconResource"].IsString) { throw new SerializationException(); }  IconResource = _buf["IconResource"]; }
    }

    public static HeroConfig DeserializeHeroConfig(JSONNode _buf)
    {
        return new HeroConfig(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 角色名称
    /// </summary>
    public readonly string HeroName;
    /// <summary>
    /// 角色战斗属性
    /// </summary>
    public readonly int HeroFightProperty;
    /// <summary>
    /// 持有物品池子
    /// </summary>
    public readonly System.Collections.Generic.List<int> InitItemPool;
    /// <summary>
    /// 物品掉落池子
    /// </summary>
    public readonly int ItemDropPool;
    /// <summary>
    /// 经验掉落
    /// </summary>
    public readonly int ExpDrop;
    /// <summary>
    /// 心法池子
    /// </summary>
    public readonly int HeartMethodPool;
    /// <summary>
    /// 武杀式池子
    /// </summary>
    public readonly int PowerKillingPool;
    /// <summary>
    /// 术杀式池子
    /// </summary>
    public readonly int ArtKillingPool;
    /// <summary>
    /// 技御式池子
    /// </summary>
    public readonly int TechniqueImperialStylePool;
    /// <summary>
    /// 法咒式池子
    /// </summary>
    public readonly int SpellFormulaPool;
    /// <summary>
    /// 额外招式池子
    /// </summary>
    public readonly int ExtraSkillPool;
    /// <summary>
    /// 战斗台词组
    /// </summary>
    public readonly int BattleLines;
    /// <summary>
    /// 战斗动作组
    /// </summary>
    public readonly int BattleAction;
    /// <summary>
    /// 头像资源
    /// </summary>
    public readonly string IconResource;
   
    public const int __ID__ = -563759108;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "HeroName:" + HeroName + ","
        + "HeroFightProperty:" + HeroFightProperty + ","
        + "InitItemPool:" + Luban.StringUtil.CollectionToString(InitItemPool) + ","
        + "ItemDropPool:" + ItemDropPool + ","
        + "ExpDrop:" + ExpDrop + ","
        + "HeartMethodPool:" + HeartMethodPool + ","
        + "PowerKillingPool:" + PowerKillingPool + ","
        + "ArtKillingPool:" + ArtKillingPool + ","
        + "TechniqueImperialStylePool:" + TechniqueImperialStylePool + ","
        + "SpellFormulaPool:" + SpellFormulaPool + ","
        + "ExtraSkillPool:" + ExtraSkillPool + ","
        + "BattleLines:" + BattleLines + ","
        + "BattleAction:" + BattleAction + ","
        + "IconResource:" + IconResource + ","
        + "}";
    }
}

}

