
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum HeroVariety
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 人
        /// </summary>
        Person = 1,
        /// <summary>
        /// 精怪
        /// </summary>
        Weird = 2,
        /// <summary>
        /// 鬼物
        /// </summary>
        Ghost = 3,
        /// <summary>
        /// 其他
        /// </summary>
        Other = 4,
    }

} 

