
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class HeroFightPropertyConfig : Luban.BeanBase
{
    public HeroFightPropertyConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["HeroID"].IsNumber) { throw new SerializationException(); }  HeroID = _buf["HeroID"]; }
        { if(!_buf["HeroName"].IsString) { throw new SerializationException(); }  HeroName = _buf["HeroName"]; }
        { var __json0 = _buf["Variety"]; if(!__json0.IsArray) { throw new SerializationException(); } Variety = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Variety.Add(__v0); }   }
        { if(!_buf["LevelLeft"].IsNumber) { throw new SerializationException(); }  LevelLeft = _buf["LevelLeft"]; }
        { if(!_buf["LevelRight"].IsNumber) { throw new SerializationException(); }  LevelRight = _buf["LevelRight"]; }
        { if(!_buf["HpBase"].IsNumber) { throw new SerializationException(); }  HpBase = _buf["HpBase"]; }
        { if(!_buf["HpUp"].IsNumber) { throw new SerializationException(); }  HpUp = _buf["HpUp"]; }
        { if(!_buf["GangQiBase"].IsNumber) { throw new SerializationException(); }  GangQiBase = _buf["GangQiBase"]; }
        { if(!_buf["GangQiUp"].IsNumber) { throw new SerializationException(); }  GangQiUp = _buf["GangQiUp"]; }
        { if(!_buf["XuanQiBase"].IsNumber) { throw new SerializationException(); }  XuanQiBase = _buf["XuanQiBase"]; }
        { if(!_buf["XuanQiUp"].IsNumber) { throw new SerializationException(); }  XuanQiUp = _buf["XuanQiUp"]; }
        { if(!_buf["PowerBase"].IsNumber) { throw new SerializationException(); }  PowerBase = _buf["PowerBase"]; }
        { if(!_buf["PowerUp"].IsNumber) { throw new SerializationException(); }  PowerUp = _buf["PowerUp"]; }
        { if(!_buf["TechBase"].IsNumber) { throw new SerializationException(); }  TechBase = _buf["TechBase"]; }
        { if(!_buf["TechUp"].IsNumber) { throw new SerializationException(); }  TechUp = _buf["TechUp"]; }
        { if(!_buf["SpeedBase"].IsNumber) { throw new SerializationException(); }  SpeedBase = _buf["SpeedBase"]; }
        { if(!_buf["SpeedUp"].IsNumber) { throw new SerializationException(); }  SpeedUp = _buf["SpeedUp"]; }
        { if(!_buf["CleverBase"].IsNumber) { throw new SerializationException(); }  CleverBase = _buf["CleverBase"]; }
        { if(!_buf["CleverUp"].IsNumber) { throw new SerializationException(); }  CleverUp = _buf["CleverUp"]; }
        { if(!_buf["DefendBase"].IsNumber) { throw new SerializationException(); }  DefendBase = _buf["DefendBase"]; }
        { if(!_buf["DefendUp"].IsNumber) { throw new SerializationException(); }  DefendUp = _buf["DefendUp"]; }
        { if(!_buf["BreakBase"].IsNumber) { throw new SerializationException(); }  BreakBase = _buf["BreakBase"]; }
        { if(!_buf["BreakUp"].IsNumber) { throw new SerializationException(); }  BreakUp = _buf["BreakUp"]; }
        { if(!_buf["KeyRecover"].IsNumber) { throw new SerializationException(); }  KeyRecover = _buf["KeyRecover"]; }
        { if(!_buf["GangQiRecoverNatural"].IsNumber) { throw new SerializationException(); }  GangQiRecoverNatural = _buf["GangQiRecoverNatural"]; }
        { if(!_buf["XuanQiRecoverNatural"].IsNumber) { throw new SerializationException(); }  XuanQiRecoverNatural = _buf["XuanQiRecoverNatural"]; }
        { if(!_buf["DieLimit"].IsNumber) { throw new SerializationException(); }  DieLimit = _buf["DieLimit"]; }
        { if(!_buf["ActionRadius"].IsNumber) { throw new SerializationException(); }  ActionRadius = _buf["ActionRadius"]; }
        { if(!_buf["ClashRadius"].IsNumber) { throw new SerializationException(); }  ClashRadius = _buf["ClashRadius"]; }
        { if(!_buf["BgmID"].IsNumber) { throw new SerializationException(); }  BgmID = _buf["BgmID"]; }
    }

    public static HeroFightPropertyConfig DeserializeHeroFightPropertyConfig(JSONNode _buf)
    {
        return new HeroFightPropertyConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 英雄ID
    /// </summary>
    public readonly int HeroID;
    /// <summary>
    /// 英雄名称
    /// </summary>
    public readonly string HeroName;
    /// <summary>
    /// 种族
    /// </summary>
    public readonly System.Collections.Generic.List<int> Variety;
    /// <summary>
    /// 等级限制左
    /// </summary>
    public readonly int LevelLeft;
    /// <summary>
    /// 等级限制右
    /// </summary>
    public readonly int LevelRight;
    /// <summary>
    /// 体基础
    /// </summary>
    public readonly float HpBase;
    /// <summary>
    /// 体成长
    /// </summary>
    public readonly float HpUp;
    /// <summary>
    /// 刚气基础
    /// </summary>
    public readonly float GangQiBase;
    /// <summary>
    /// 刚气成长
    /// </summary>
    public readonly float GangQiUp;
    /// <summary>
    /// 玄气基础
    /// </summary>
    public readonly float XuanQiBase;
    /// <summary>
    /// 玄气成长
    /// </summary>
    public readonly float XuanQiUp;
    /// <summary>
    /// 力基础
    /// </summary>
    public readonly float PowerBase;
    /// <summary>
    /// 力成长
    /// </summary>
    public readonly float PowerUp;
    /// <summary>
    /// 技基础
    /// </summary>
    public readonly float TechBase;
    /// <summary>
    /// 技成长
    /// </summary>
    public readonly float TechUp;
    /// <summary>
    /// 速基础
    /// </summary>
    public readonly float SpeedBase;
    /// <summary>
    /// 速成长
    /// </summary>
    public readonly float SpeedUp;
    /// <summary>
    /// 巧基础
    /// </summary>
    public readonly float CleverBase;
    /// <summary>
    /// 巧成长
    /// </summary>
    public readonly float CleverUp;
    /// <summary>
    /// 防基础
    /// </summary>
    public readonly float DefendBase;
    /// <summary>
    /// 防成长
    /// </summary>
    public readonly float DefendUp;
    /// <summary>
    /// 破基础
    /// </summary>
    public readonly float BreakBase;
    /// <summary>
    /// 破成长
    /// </summary>
    public readonly float BreakUp;
    /// <summary>
    /// 键恢复
    /// </summary>
    public readonly int KeyRecover;
    /// <summary>
    /// 刚气自然恢复
    /// </summary>
    public readonly float GangQiRecoverNatural;
    /// <summary>
    /// 玄气自然恢复
    /// </summary>
    public readonly float XuanQiRecoverNatural;
    /// <summary>
    /// 死限
    /// </summary>
    public readonly int DieLimit;
    /// <summary>
    /// 单方面点半径
    /// </summary>
    public readonly float ActionRadius;
    /// <summary>
    /// 交锋点半径
    /// </summary>
    public readonly float ClashRadius;
    /// <summary>
    /// BGM变更
    /// </summary>
    public readonly int BgmID;
   
    public const int __ID__ = -534725843;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "HeroID:" + HeroID + ","
        + "HeroName:" + HeroName + ","
        + "Variety:" + Luban.StringUtil.CollectionToString(Variety) + ","
        + "LevelLeft:" + LevelLeft + ","
        + "LevelRight:" + LevelRight + ","
        + "HpBase:" + HpBase + ","
        + "HpUp:" + HpUp + ","
        + "GangQiBase:" + GangQiBase + ","
        + "GangQiUp:" + GangQiUp + ","
        + "XuanQiBase:" + XuanQiBase + ","
        + "XuanQiUp:" + XuanQiUp + ","
        + "PowerBase:" + PowerBase + ","
        + "PowerUp:" + PowerUp + ","
        + "TechBase:" + TechBase + ","
        + "TechUp:" + TechUp + ","
        + "SpeedBase:" + SpeedBase + ","
        + "SpeedUp:" + SpeedUp + ","
        + "CleverBase:" + CleverBase + ","
        + "CleverUp:" + CleverUp + ","
        + "DefendBase:" + DefendBase + ","
        + "DefendUp:" + DefendUp + ","
        + "BreakBase:" + BreakBase + ","
        + "BreakUp:" + BreakUp + ","
        + "KeyRecover:" + KeyRecover + ","
        + "GangQiRecoverNatural:" + GangQiRecoverNatural + ","
        + "XuanQiRecoverNatural:" + XuanQiRecoverNatural + ","
        + "DieLimit:" + DieLimit + ","
        + "ActionRadius:" + ActionRadius + ","
        + "ClashRadius:" + ClashRadius + ","
        + "BgmID:" + BgmID + ","
        + "}";
    }
}

}

