
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class MapConfig : Luban.BeanBase
{
    public MapConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["MapName"].IsString) { throw new SerializationException(); }  MapName = _buf["MapName"]; }
        { if(!_buf["WorldID"].IsNumber) { throw new SerializationException(); }  WorldID = _buf["WorldID"]; }
        { if(!_buf["Position"].IsObject) { throw new SerializationException(); }  Position = global::cfg.Position.DeserializePosition(_buf["Position"]);  }
        { var __json0 = _buf["NeighMap"]; if(!__json0.IsArray) { throw new SerializationException(); } NeighMap = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NeighMap.Add(__v0); }   }
        { if(!_buf["MapResource"].IsString) { throw new SerializationException(); }  MapResource = _buf["MapResource"]; }
        { if(!_buf["WorldResource"].IsString) { throw new SerializationException(); }  WorldResource = _buf["WorldResource"]; }
    }

    public static MapConfig DeserializeMapConfig(JSONNode _buf)
    {
        return new MapConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 地图名称
    /// </summary>
    public readonly string MapName;
    /// <summary>
    /// 所在世界ID
    /// </summary>
    public readonly int WorldID;
    /// <summary>
    /// 地图显示位置
    /// </summary>
    public readonly Position Position;
    /// <summary>
    /// 相邻的县(县就是地图)
    /// </summary>
    public readonly System.Collections.Generic.List<int> NeighMap;
    /// <summary>
    /// 地图资源
    /// </summary>
    public readonly string MapResource;
    /// <summary>
    /// 位于大世界的地图资源
    /// </summary>
    public readonly string WorldResource;
   
    public const int __ID__ = -1840922722;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Position?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "MapName:" + MapName + ","
        + "WorldID:" + WorldID + ","
        + "Position:" + Position + ","
        + "NeighMap:" + Luban.StringUtil.CollectionToString(NeighMap) + ","
        + "MapResource:" + MapResource + ","
        + "WorldResource:" + WorldResource + ","
        + "}";
    }
}

}

