
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class NarratorDialogueConfig : Luban.BeanBase
{
    public NarratorDialogueConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Content"].IsString) { throw new SerializationException(); }  Content = _buf["Content"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["TriggerMethod"].IsNumber) { throw new SerializationException(); }  TriggerMethod = _buf["TriggerMethod"]; }
        { if(!_buf["ConditionID"].IsNumber) { throw new SerializationException(); }  ConditionID = _buf["ConditionID"]; }
        { var __json0 = _buf["ConditionParam"]; if(!__json0.IsArray) { throw new SerializationException(); } ConditionParam = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ConditionParam.Add(__v0); }   }
    }

    public static NarratorDialogueConfig DeserializeNarratorDialogueConfig(JSONNode _buf)
    {
        return new NarratorDialogueConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 内容
    /// </summary>
    public readonly string Content;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 触发方式
    /// </summary>
    public readonly int TriggerMethod;
    /// <summary>
    /// 条件ID
    /// </summary>
    public readonly int ConditionID;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> ConditionParam;
   
    public const int __ID__ = 1259273923;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Content:" + Content + ","
        + "Weight:" + Weight + ","
        + "TriggerMethod:" + TriggerMethod + ","
        + "ConditionID:" + ConditionID + ","
        + "ConditionParam:" + Luban.StringUtil.CollectionToString(ConditionParam) + ","
        + "}";
    }
}

}

