
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PasserbyInSceneData : Luban.BeanBase
{
    public PasserbyInSceneData(JSONNode _buf) 
    {
        { if(!_buf["SceneID"].IsNumber) { throw new SerializationException(); }  SceneID = _buf["SceneID"]; }
        { if(!_buf["X"].IsNumber) { throw new SerializationException(); }  X = _buf["X"]; }
        { if(!_buf["Y"].IsNumber) { throw new SerializationException(); }  Y = _buf["Y"]; }
    }

    public static PasserbyInSceneData DeserializePasserbyInSceneData(JSONNode _buf)
    {
        return new PasserbyInSceneData(_buf);
    }

    /// <summary>
    /// 场景ID
    /// </summary>
    public readonly int SceneID;
    public readonly float X;
    public readonly float Y;
   
    public const int __ID__ = -1777138180;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SceneID:" + SceneID + ","
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}

}

