
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class PasserbyConfig : Luban.BeanBase
{
    public PasserbyConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { var __json0 = _buf["SceneLocation"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; SceneLocation = new PasserbyInSceneData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { PasserbyInSceneData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.PasserbyInSceneData.DeserializePasserbyInSceneData(__e0);  }  SceneLocation[__index0++] = __v0; }   }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["TimePeriod"].IsObject) { throw new SerializationException(); }  TimePeriod = global::cfg.TimePeriod.DeserializeTimePeriod(_buf["TimePeriod"]);  }
        { var __json0 = _buf["TriggerDate"]; if(!__json0.IsArray) { throw new SerializationException(); } TriggerDate = new System.Collections.Generic.Dictionary<int, float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } float _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  TriggerDate.Add(_k0, _v0); }   }
        { if(!_buf["ConditionID"].IsNumber) { throw new SerializationException(); }  ConditionID = _buf["ConditionID"]; }
        { var __json0 = _buf["ConditionParam"]; if(!__json0.IsArray) { throw new SerializationException(); } ConditionParam = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ConditionParam.Add(__v0); }   }
        { if(!_buf["TriggerInterval"].IsNumber) { throw new SerializationException(); }  TriggerInterval = _buf["TriggerInterval"]; }
        { if(!_buf["Resource"].IsString) { throw new SerializationException(); }  Resource = _buf["Resource"]; }
    }

    public static PasserbyConfig DeserializePasserbyConfig(JSONNode _buf)
    {
        return new PasserbyConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 所在场景(场景id,x坐标,y坐标)复数
    /// </summary>
    public readonly PasserbyInSceneData[] SceneLocation;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 时间段
    /// </summary>
    public readonly TimePeriod TimePeriod;
    /// <summary>
    /// 可触发的日期(参数格式为-1|x（每日|概率百分比）或日期类型id|x（指定类型的日期|概率百分比），可同时存在多个参数，逗号相隔，仅从满足的中选概率最高的进行触发判定)
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, float> TriggerDate;
    /// <summary>
    /// 条件ID
    /// </summary>
    public readonly int ConditionID;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<int> ConditionParam;
    /// <summary>
    /// 触发间隔
    /// </summary>
    public readonly int TriggerInterval;
    /// <summary>
    /// 美术资源
    /// </summary>
    public readonly string Resource;
   
    public const int __ID__ = -241517289;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in SceneLocation) { _e?.ResolveRef(tables); }
        TimePeriod?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Name:" + Name + ","
        + "SceneLocation:" + Luban.StringUtil.CollectionToString(SceneLocation) + ","
        + "Weight:" + Weight + ","
        + "TimePeriod:" + TimePeriod + ","
        + "TriggerDate:" + Luban.StringUtil.CollectionToString(TriggerDate) + ","
        + "ConditionID:" + ConditionID + ","
        + "ConditionParam:" + Luban.StringUtil.CollectionToString(ConditionParam) + ","
        + "TriggerInterval:" + TriggerInterval + ","
        + "Resource:" + Resource + ","
        + "}";
    }
}

}

