
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class Position : Luban.BeanBase
{
    public Position(JSONNode _buf) 
    {
        { if(!_buf["X"].IsNumber) { throw new SerializationException(); }  X = _buf["X"]; }
        { if(!_buf["Y"].IsNumber) { throw new SerializationException(); }  Y = _buf["Y"]; }
    }

    public static Position DeserializePosition(JSONNode _buf)
    {
        return new Position(_buf);
    }

    /// <summary>
    /// 位置X
    /// </summary>
    public readonly float X;
    /// <summary>
    /// 位置Y
    /// </summary>
    public readonly float Y;
   
    public const int __ID__ = 812449097;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}

}

