
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ScenePassageData : Luban.BeanBase
{
    public ScenePassageData(JSONNode _buf) 
    {
        { if(!_buf["PassageID"].IsNumber) { throw new SerializationException(); }  PassageID = _buf["PassageID"]; }
        { if(!_buf["X"].IsNumber) { throw new SerializationException(); }  X = _buf["X"]; }
        { if(!_buf["Y"].IsNumber) { throw new SerializationException(); }  Y = _buf["Y"]; }
    }

    public static ScenePassageData DeserializeScenePassageData(JSONNode _buf)
    {
        return new ScenePassageData(_buf);
    }

    public readonly int PassageID;
    public readonly float X;
    public readonly float Y;
   
    public const int __ID__ = -1595367412;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "PassageID:" + PassageID + ","
        + "X:" + X + ","
        + "Y:" + Y + ","
        + "}";
    }
}

}

