
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SceneFloorPosition : Luban.BeanBase
{
    public SceneFloorPosition(JSONNode _buf) 
    {
        { if(!_buf["X1"].IsNumber) { throw new SerializationException(); }  X1 = _buf["X1"]; }
        { if(!_buf["Y1"].IsNumber) { throw new SerializationException(); }  Y1 = _buf["Y1"]; }
        { if(!_buf["X2"].IsNumber) { throw new SerializationException(); }  X2 = _buf["X2"]; }
        { if(!_buf["Y2"].IsNumber) { throw new SerializationException(); }  Y2 = _buf["Y2"]; }
    }

    public static SceneFloorPosition DeserializeSceneFloorPosition(JSONNode _buf)
    {
        return new SceneFloorPosition(_buf);
    }

    public readonly float X1;
    public readonly float Y1;
    public readonly float X2;
    public readonly float Y2;
   
    public const int __ID__ = -855675831;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "X1:" + X1 + ","
        + "Y1:" + Y1 + ","
        + "X2:" + X2 + ","
        + "Y2:" + Y2 + ","
        + "}";
    }
}

}

