
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SceneInteractionItemConfig : Luban.BeanBase
{
    public SceneInteractionItemConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["IconResource"].IsString) { throw new SerializationException(); }  IconResource = _buf["IconResource"]; }
        { if(!_buf["TriggerFunc"].IsNumber) { throw new SerializationException(); }  TriggerFunc = _buf["TriggerFunc"]; }
    }

    public static SceneInteractionItemConfig DeserializeSceneInteractionItemConfig(JSONNode _buf)
    {
        return new SceneInteractionItemConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 图标资源
    /// </summary>
    public readonly string IconResource;
    /// <summary>
    /// 触发的功能ID
    /// </summary>
    public readonly int TriggerFunc;
   
    public const int __ID__ = 1770041051;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "IconResource:" + IconResource + ","
        + "TriggerFunc:" + TriggerFunc + ","
        + "}";
    }
}

}

