
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SceneConfig : Luban.BeanBase
{
    public SceneConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["SceneName"].IsString) { throw new SerializationException(); }  SceneName = _buf["SceneName"]; }
        { if(!_buf["ZoneID"].IsNumber) { throw new SerializationException(); }  ZoneID = _buf["ZoneID"]; }
        { if(!_buf["ZoneName"].IsString) { throw new SerializationException(); }  ZoneName = _buf["ZoneName"]; }
        { var __json0 = _buf["InteractionItem"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; InteractionItem = new SceneInteractionItemData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { SceneInteractionItemData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SceneInteractionItemData.DeserializeSceneInteractionItemData(__e0);  }  InteractionItem[__index0++] = __v0; }   }
        { if(!_buf["MiniMapPos"].IsObject) { throw new SerializationException(); }  MiniMapPos = global::cfg.Position.DeserializePosition(_buf["MiniMapPos"]);  }
        { if(!_buf["PlayerGenPos"].IsObject) { throw new SerializationException(); }  PlayerGenPos = global::cfg.Position.DeserializePosition(_buf["PlayerGenPos"]);  }
        { var __json0 = _buf["PasserByGenPos"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; PasserByGenPos = new Position[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { Position __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.Position.DeserializePosition(__e0);  }  PasserByGenPos[__index0++] = __v0; }   }
        { var __json0 = _buf["FloorGenPos"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; FloorGenPos = new SceneFloorPosition[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { SceneFloorPosition __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.SceneFloorPosition.DeserializeSceneFloorPosition(__e0);  }  FloorGenPos[__index0++] = __v0; }   }
        { var __json0 = _buf["Passage"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; Passage = new ScenePassageData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { ScenePassageData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.ScenePassageData.DeserializeScenePassageData(__e0);  }  Passage[__index0++] = __v0; }   }
        { if(!_buf["DefaultShowInMap"].IsNumber) { throw new SerializationException(); }  DefaultShowInMap = _buf["DefaultShowInMap"]; }
        { if(!_buf["SceneType"].IsNumber) { throw new SerializationException(); }  SceneType = _buf["SceneType"]; }
        { if(!_buf["ForeMap"].IsNumber) { throw new SerializationException(); }  ForeMap = _buf["ForeMap"]; }
        { if(!_buf["BackgroundResource"].IsString) { throw new SerializationException(); }  BackgroundResource = _buf["BackgroundResource"]; }
        { if(!_buf["ForegroundResource"].IsString) { throw new SerializationException(); }  ForegroundResource = _buf["ForegroundResource"]; }
    }

    public static SceneConfig DeserializeSceneConfig(JSONNode _buf)
    {
        return new SceneConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 场景名
    /// </summary>
    public readonly string SceneName;
    /// <summary>
    /// 归属地区ID
    /// </summary>
    public readonly int ZoneID;
    /// <summary>
    /// 归属地区名称
    /// </summary>
    public readonly string ZoneName;
    /// <summary>
    /// 默认场景物品交互(ID:SceneInteractionItemConfig)
    /// </summary>
    public readonly SceneInteractionItemData[] InteractionItem;
    /// <summary>
    /// 小地图显示位置
    /// </summary>
    public readonly Position MiniMapPos;
    /// <summary>
    /// 主角生成坐标
    /// </summary>
    public readonly Position PlayerGenPos;
    /// <summary>
    /// 路人生成坐标
    /// </summary>
    public readonly Position[] PasserByGenPos;
    /// <summary>
    /// 地板坐标
    /// </summary>
    public readonly SceneFloorPosition[] FloorGenPos;
    /// <summary>
    /// 默认场景物品交互(ID:ScenePassageConfig)
    /// </summary>
    public readonly ScenePassageData[] Passage;
    /// <summary>
    /// 默认是否显示于小地图
    /// </summary>
    public readonly int DefaultShowInMap;
    /// <summary>
    /// 场景类型(场景类型表)
    /// </summary>
    public readonly int SceneType;
    /// <summary>
    /// 前置地图(条件处理器)
    /// </summary>
    public readonly int ForeMap;
    /// <summary>
    /// 背景美术资源
    /// </summary>
    public readonly string BackgroundResource;
    /// <summary>
    /// 前景美术资源
    /// </summary>
    public readonly string ForegroundResource;
   
    public const int __ID__ = 935827150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in InteractionItem) { _e?.ResolveRef(tables); }
        MiniMapPos?.ResolveRef(tables);
        PlayerGenPos?.ResolveRef(tables);
        foreach (var _e in PasserByGenPos) { _e?.ResolveRef(tables); }
        foreach (var _e in FloorGenPos) { _e?.ResolveRef(tables); }
        foreach (var _e in Passage) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SceneName:" + SceneName + ","
        + "ZoneID:" + ZoneID + ","
        + "ZoneName:" + ZoneName + ","
        + "InteractionItem:" + Luban.StringUtil.CollectionToString(InteractionItem) + ","
        + "MiniMapPos:" + MiniMapPos + ","
        + "PlayerGenPos:" + PlayerGenPos + ","
        + "PasserByGenPos:" + Luban.StringUtil.CollectionToString(PasserByGenPos) + ","
        + "FloorGenPos:" + Luban.StringUtil.CollectionToString(FloorGenPos) + ","
        + "Passage:" + Luban.StringUtil.CollectionToString(Passage) + ","
        + "DefaultShowInMap:" + DefaultShowInMap + ","
        + "SceneType:" + SceneType + ","
        + "ForeMap:" + ForeMap + ","
        + "BackgroundResource:" + BackgroundResource + ","
        + "ForegroundResource:" + ForegroundResource + ","
        + "}";
    }
}

}

