
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class SeasonConfig : Luban.BeanBase
{
    public SeasonConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["SeasonType"].IsString) { throw new SerializationException(); }  SeasonType = _buf["SeasonType"]; }
    }

    public static SeasonConfig DeserializeSeasonConfig(JSONNode _buf)
    {
        return new SeasonConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 季节类型
    /// </summary>
    public readonly string SeasonType;
   
    public const int __ID__ = -1516685275;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "SeasonType:" + SeasonType + ","
        + "}";
    }
}

}

