
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 武杀式
        /// </summary>
        PowerKilling = 1,
        /// <summary>
        /// 术杀式
        /// </summary>
        ArtKilling = 2,
        /// <summary>
        /// 技御式
        /// </summary>
        TechniqueImperialStyle = 3,
        /// <summary>
        /// 法咒式
        /// </summary>
        SpellFormula = 4,
    }

} 

