
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillDataGetType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 技能预先消耗
        /// </summary>
        CostPreview = 1,
        /// <summary>
        /// 技能检测消耗
        /// </summary>
        CheckCost = 2,
        /// <summary>
        /// 技能释放消耗
        /// </summary>
        ReleaseCost = 3,
        /// <summary>
        /// 技能预先伤害
        /// </summary>
        DamagePreview = 4,
        /// <summary>
        /// 技能基础伤害
        /// </summary>
        DamageBase = 5,
        /// <summary>
        /// 技能当前伤害
        /// </summary>
        DamageCurr = 6,
        /// <summary>
        /// 技能预先键
        /// </summary>
        KeyPreview = 7,
        /// <summary>
        /// 技能检测键
        /// </summary>
        CheckKey = 8,
        /// <summary>
        /// 技能消耗键
        /// </summary>
        ReleaseKey = 9,
    }

} 

