
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum SkillRemoveMomentType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 行动后
        /// </summary>
        AfterAction = 1,
        /// <summary>
        /// 下次行动前
        /// </summary>
        BeforeNextAction = 2,
        /// <summary>
        /// 这个回合结束
        /// </summary>
        RoundEnd = 3,
        /// <summary>
        /// 破招
        /// </summary>
        BeCounter = 4,
        /// <summary>
        /// 下个回合开始
        /// </summary>
        NextRoundStart = 5,
    }

} 

