
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbBattleBuffConfig TbBattleBuffConfig {get; }
    public TbBattleBuffRelationConfig TbBattleBuffRelationConfig {get; }
    public TbBattleMomentConditionConfig TbBattleMomentConditionConfig {get; }
    public TbBattleMomentConfig TbBattleMomentConfig {get; }
    public TbBattleMomentEffectConfig TbBattleMomentEffectConfig {get; }
    public TbBattleSkillConfig TbBattleSkillConfig {get; }
    public TbHeartMethodConfig TbHeartMethodConfig {get; }
    public TbItemConfig TbItemConfig {get; }
    public TbTreasureConfig TbTreasureConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBattleBuffConfig = new TbBattleBuffConfig(loader("tbbattlebuffconfig"));
        TbBattleBuffRelationConfig = new TbBattleBuffRelationConfig(loader("tbbattlebuffrelationconfig"));
        TbBattleMomentConditionConfig = new TbBattleMomentConditionConfig(loader("tbbattlemomentconditionconfig"));
        TbBattleMomentConfig = new TbBattleMomentConfig(loader("tbbattlemomentconfig"));
        TbBattleMomentEffectConfig = new TbBattleMomentEffectConfig(loader("tbbattlemomenteffectconfig"));
        TbBattleSkillConfig = new TbBattleSkillConfig(loader("tbbattleskillconfig"));
        TbHeartMethodConfig = new TbHeartMethodConfig(loader("tbheartmethodconfig"));
        TbItemConfig = new TbItemConfig(loader("tbitemconfig"));
        TbTreasureConfig = new TbTreasureConfig(loader("tbtreasureconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBattleBuffConfig.ResolveRef(this);
        TbBattleBuffRelationConfig.ResolveRef(this);
        TbBattleMomentConditionConfig.ResolveRef(this);
        TbBattleMomentConfig.ResolveRef(this);
        TbBattleMomentEffectConfig.ResolveRef(this);
        TbBattleSkillConfig.ResolveRef(this);
        TbHeartMethodConfig.ResolveRef(this);
        TbItemConfig.ResolveRef(this);
        TbTreasureConfig.ResolveRef(this);
    }
}

}
