
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public TbBattleBuffConfig TbBattleBuffConfig {get; }
    public TbBattleBuffRelationConfig TbBattleBuffRelationConfig {get; }
    public TbBattleMomentConditionConfig TbBattleMomentConditionConfig {get; }
    public TbBattleMomentConfig TbBattleMomentConfig {get; }
    public TbBattleMomentEffectConfig TbBattleMomentEffectConfig {get; }
    public TbBattleSkillConfig TbBattleSkillConfig {get; }
    public TbConditionConfig TbConditionConfig {get; }
    public TbDateConfig TbDateConfig {get; }
    public TbDateTypeConfig TbDateTypeConfig {get; }
    public TbHeartMethodConfig TbHeartMethodConfig {get; }
    public TbItemConfig TbItemConfig {get; }
    public TbMapConfig TbMapConfig {get; }
    public TbNarratorDialogueConfig TbNarratorDialogueConfig {get; }
    public TbPasserbyConfig TbPasserbyConfig {get; }
    public TbSceneConfig TbSceneConfig {get; }
    public TbSceneInteractionItemConfig TbSceneInteractionItemConfig {get; }
    public TbScenePassageConfig TbScenePassageConfig {get; }
    public TbSceneTypeConfig TbSceneTypeConfig {get; }
    public TbSeasonConfig TbSeasonConfig {get; }
    public TbTimeCostConfig TbTimeCostConfig {get; }
    public TbTravelEventConditionConfig TbTravelEventConditionConfig {get; }
    public TbTravelEventConfig TbTravelEventConfig {get; }
    public TbTreasureConfig TbTreasureConfig {get; }
    public TbWeatherConfig TbWeatherConfig {get; }
    public TbWeatherGroupConfig TbWeatherGroupConfig {get; }
    public TbWeatherPoolConfig TbWeatherPoolConfig {get; }
    public TbZoneConfig TbZoneConfig {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbBattleBuffConfig = new TbBattleBuffConfig(loader("tbbattlebuffconfig"));
        TbBattleBuffRelationConfig = new TbBattleBuffRelationConfig(loader("tbbattlebuffrelationconfig"));
        TbBattleMomentConditionConfig = new TbBattleMomentConditionConfig(loader("tbbattlemomentconditionconfig"));
        TbBattleMomentConfig = new TbBattleMomentConfig(loader("tbbattlemomentconfig"));
        TbBattleMomentEffectConfig = new TbBattleMomentEffectConfig(loader("tbbattlemomenteffectconfig"));
        TbBattleSkillConfig = new TbBattleSkillConfig(loader("tbbattleskillconfig"));
        TbConditionConfig = new TbConditionConfig(loader("tbconditionconfig"));
        TbDateConfig = new TbDateConfig(loader("tbdateconfig"));
        TbDateTypeConfig = new TbDateTypeConfig(loader("tbdatetypeconfig"));
        TbHeartMethodConfig = new TbHeartMethodConfig(loader("tbheartmethodconfig"));
        TbItemConfig = new TbItemConfig(loader("tbitemconfig"));
        TbMapConfig = new TbMapConfig(loader("tbmapconfig"));
        TbNarratorDialogueConfig = new TbNarratorDialogueConfig(loader("tbnarratordialogueconfig"));
        TbPasserbyConfig = new TbPasserbyConfig(loader("tbpasserbyconfig"));
        TbSceneConfig = new TbSceneConfig(loader("tbsceneconfig"));
        TbSceneInteractionItemConfig = new TbSceneInteractionItemConfig(loader("tbsceneinteractionitemconfig"));
        TbScenePassageConfig = new TbScenePassageConfig(loader("tbscenepassageconfig"));
        TbSceneTypeConfig = new TbSceneTypeConfig(loader("tbscenetypeconfig"));
        TbSeasonConfig = new TbSeasonConfig(loader("tbseasonconfig"));
        TbTimeCostConfig = new TbTimeCostConfig(loader("tbtimecostconfig"));
        TbTravelEventConditionConfig = new TbTravelEventConditionConfig(loader("tbtraveleventconditionconfig"));
        TbTravelEventConfig = new TbTravelEventConfig(loader("tbtraveleventconfig"));
        TbTreasureConfig = new TbTreasureConfig(loader("tbtreasureconfig"));
        TbWeatherConfig = new TbWeatherConfig(loader("tbweatherconfig"));
        TbWeatherGroupConfig = new TbWeatherGroupConfig(loader("tbweathergroupconfig"));
        TbWeatherPoolConfig = new TbWeatherPoolConfig(loader("tbweatherpoolconfig"));
        TbZoneConfig = new TbZoneConfig(loader("tbzoneconfig"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbBattleBuffConfig.ResolveRef(this);
        TbBattleBuffRelationConfig.ResolveRef(this);
        TbBattleMomentConditionConfig.ResolveRef(this);
        TbBattleMomentConfig.ResolveRef(this);
        TbBattleMomentEffectConfig.ResolveRef(this);
        TbBattleSkillConfig.ResolveRef(this);
        TbConditionConfig.ResolveRef(this);
        TbDateConfig.ResolveRef(this);
        TbDateTypeConfig.ResolveRef(this);
        TbHeartMethodConfig.ResolveRef(this);
        TbItemConfig.ResolveRef(this);
        TbMapConfig.ResolveRef(this);
        TbNarratorDialogueConfig.ResolveRef(this);
        TbPasserbyConfig.ResolveRef(this);
        TbSceneConfig.ResolveRef(this);
        TbSceneInteractionItemConfig.ResolveRef(this);
        TbScenePassageConfig.ResolveRef(this);
        TbSceneTypeConfig.ResolveRef(this);
        TbSeasonConfig.ResolveRef(this);
        TbTimeCostConfig.ResolveRef(this);
        TbTravelEventConditionConfig.ResolveRef(this);
        TbTravelEventConfig.ResolveRef(this);
        TbTreasureConfig.ResolveRef(this);
        TbWeatherConfig.ResolveRef(this);
        TbWeatherGroupConfig.ResolveRef(this);
        TbWeatherPoolConfig.ResolveRef(this);
        TbZoneConfig.ResolveRef(this);
    }
}

}
