
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleSkillConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleSkillConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleSkillConfig> _dataList;
    
    public TbBattleSkillConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleSkillConfig>();
        _dataList = new System.Collections.Generic.List<BattleSkillConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleSkillConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleSkillConfig.DeserializeBattleSkillConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleSkillConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleSkillConfig> DataList => _dataList;

    public BattleSkillConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleSkillConfig Get(int key) => _dataMap[key];
    public BattleSkillConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

