
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleMomentConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleMomentConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleMomentConfig> _dataList;
    
    public TbBattleMomentConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleMomentConfig>();
        _dataList = new System.Collections.Generic.List<BattleMomentConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleMomentConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleMomentConfig.DeserializeBattleMomentConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleMomentConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleMomentConfig> DataList => _dataList;

    public BattleMomentConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleMomentConfig Get(int key) => _dataMap[key];
    public BattleMomentConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

