
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleBuffRelationConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleBuffRelationConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleBuffRelationConfig> _dataList;
    
    public TbBattleBuffRelationConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleBuffRelationConfig>();
        _dataList = new System.Collections.Generic.List<BattleBuffRelationConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleBuffRelationConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleBuffRelationConfig.DeserializeBattleBuffRelationConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleBuffRelationConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleBuffRelationConfig> DataList => _dataList;

    public BattleBuffRelationConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleBuffRelationConfig Get(int key) => _dataMap[key];
    public BattleBuffRelationConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

