
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleVariantConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleVariantConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleVariantConfig> _dataList;
    
    public TbBattleVariantConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleVariantConfig>();
        _dataList = new System.Collections.Generic.List<BattleVariantConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleVariantConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleVariantConfig.DeserializeBattleVariantConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleVariantConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleVariantConfig> DataList => _dataList;

    public BattleVariantConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleVariantConfig Get(int key) => _dataMap[key];
    public BattleVariantConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

