
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleBuffConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleBuffConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleBuffConfig> _dataList;
    
    public TbBattleBuffConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleBuffConfig>();
        _dataList = new System.Collections.Generic.List<BattleBuffConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleBuffConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleBuffConfig.DeserializeBattleBuffConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleBuffConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleBuffConfig> DataList => _dataList;

    public BattleBuffConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleBuffConfig Get(int key) => _dataMap[key];
    public BattleBuffConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

