
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleWeatherConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleWeatherConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleWeatherConfig> _dataList;
    
    public TbBattleWeatherConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleWeatherConfig>();
        _dataList = new System.Collections.Generic.List<BattleWeatherConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleWeatherConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleWeatherConfig.DeserializeBattleWeatherConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleWeatherConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleWeatherConfig> DataList => _dataList;

    public BattleWeatherConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleWeatherConfig Get(int key) => _dataMap[key];
    public BattleWeatherConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

