
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleMomentConditionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleMomentConditionConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleMomentConditionConfig> _dataList;
    
    public TbBattleMomentConditionConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleMomentConditionConfig>();
        _dataList = new System.Collections.Generic.List<BattleMomentConditionConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleMomentConditionConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleMomentConditionConfig.DeserializeBattleMomentConditionConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleMomentConditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleMomentConditionConfig> DataList => _dataList;

    public BattleMomentConditionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleMomentConditionConfig Get(int key) => _dataMap[key];
    public BattleMomentConditionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

