
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleMomentEffectConfig
{
    private readonly System.Collections.Generic.Dictionary<int, BattleMomentEffectConfig> _dataMap;
    private readonly System.Collections.Generic.List<BattleMomentEffectConfig> _dataList;
    
    public TbBattleMomentEffectConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleMomentEffectConfig>();
        _dataList = new System.Collections.Generic.List<BattleMomentEffectConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleMomentEffectConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleMomentEffectConfig.DeserializeBattleMomentEffectConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleMomentEffectConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleMomentEffectConfig> DataList => _dataList;

    public BattleMomentEffectConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleMomentEffectConfig Get(int key) => _dataMap[key];
    public BattleMomentEffectConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

