
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbDateTypeConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DateTypeConfig> _dataMap;
    private readonly System.Collections.Generic.List<DateTypeConfig> _dataList;
    
    public TbDateTypeConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DateTypeConfig>();
        _dataList = new System.Collections.Generic.List<DateTypeConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DateTypeConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.DateTypeConfig.DeserializeDateTypeConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DateTypeConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DateTypeConfig> DataList => _dataList;

    public DateTypeConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DateTypeConfig Get(int key) => _dataMap[key];
    public DateTypeConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

