
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbDateConfig
{
    private readonly System.Collections.Generic.Dictionary<int, DateConfig> _dataMap;
    private readonly System.Collections.Generic.List<DateConfig> _dataList;
    
    public TbDateConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, DateConfig>();
        _dataList = new System.Collections.Generic.List<DateConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            DateConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.DateConfig.DeserializeDateConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, DateConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<DateConfig> DataList => _dataList;

    public DateConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public DateConfig Get(int key) => _dataMap[key];
    public DateConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

