
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHeartMethodConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HeartMethodConfig> _dataMap;
    private readonly System.Collections.Generic.List<HeartMethodConfig> _dataList;
    
    public TbHeartMethodConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeartMethodConfig>();
        _dataList = new System.Collections.Generic.List<HeartMethodConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeartMethodConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.HeartMethodConfig.DeserializeHeartMethodConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeartMethodConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<HeartMethodConfig> DataList => _dataList;

    public HeartMethodConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeartMethodConfig Get(int key) => _dataMap[key];
    public HeartMethodConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

