
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHeroConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HeroConfig> _dataMap;
    private readonly System.Collections.Generic.List<HeroConfig> _dataList;
    
    public TbHeroConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroConfig>();
        _dataList = new System.Collections.Generic.List<HeroConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeroConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.HeroConfig.DeserializeHeroConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroConfig> DataList => _dataList;

    public HeroConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroConfig Get(int key) => _dataMap[key];
    public HeroConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

