
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHeroFightPropertyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, HeroFightPropertyConfig> _dataMap;
    private readonly System.Collections.Generic.List<HeroFightPropertyConfig> _dataList;
    
    public TbHeroFightPropertyConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeroFightPropertyConfig>();
        _dataList = new System.Collections.Generic.List<HeroFightPropertyConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeroFightPropertyConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.HeroFightPropertyConfig.DeserializeHeroFightPropertyConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeroFightPropertyConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<HeroFightPropertyConfig> DataList => _dataList;

    public HeroFightPropertyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeroFightPropertyConfig Get(int key) => _dataMap[key];
    public HeroFightPropertyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

