
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbNarratorDialogueConfig
{
    private readonly System.Collections.Generic.Dictionary<int, NarratorDialogueConfig> _dataMap;
    private readonly System.Collections.Generic.List<NarratorDialogueConfig> _dataList;
    
    public TbNarratorDialogueConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, NarratorDialogueConfig>();
        _dataList = new System.Collections.Generic.List<NarratorDialogueConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            NarratorDialogueConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.NarratorDialogueConfig.DeserializeNarratorDialogueConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, NarratorDialogueConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<NarratorDialogueConfig> DataList => _dataList;

    public NarratorDialogueConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public NarratorDialogueConfig Get(int key) => _dataMap[key];
    public NarratorDialogueConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

