
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbPasserbyConfig
{
    private readonly System.Collections.Generic.Dictionary<int, PasserbyConfig> _dataMap;
    private readonly System.Collections.Generic.List<PasserbyConfig> _dataList;
    
    public TbPasserbyConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, PasserbyConfig>();
        _dataList = new System.Collections.Generic.List<PasserbyConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            PasserbyConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.PasserbyConfig.DeserializePasserbyConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, PasserbyConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<PasserbyConfig> DataList => _dataList;

    public PasserbyConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public PasserbyConfig Get(int key) => _dataMap[key];
    public PasserbyConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

