
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbSceneInteractionItemConfig
{
    private readonly System.Collections.Generic.Dictionary<int, SceneInteractionItemConfig> _dataMap;
    private readonly System.Collections.Generic.List<SceneInteractionItemConfig> _dataList;
    
    public TbSceneInteractionItemConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, SceneInteractionItemConfig>();
        _dataList = new System.Collections.Generic.List<SceneInteractionItemConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SceneInteractionItemConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.SceneInteractionItemConfig.DeserializeSceneInteractionItemConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, SceneInteractionItemConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<SceneInteractionItemConfig> DataList => _dataList;

    public SceneInteractionItemConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SceneInteractionItemConfig Get(int key) => _dataMap[key];
    public SceneInteractionItemConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

