
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbScenePassageConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ScenePassageConfig> _dataMap;
    private readonly System.Collections.Generic.List<ScenePassageConfig> _dataList;
    
    public TbScenePassageConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ScenePassageConfig>();
        _dataList = new System.Collections.Generic.List<ScenePassageConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ScenePassageConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ScenePassageConfig.DeserializeScenePassageConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ScenePassageConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ScenePassageConfig> DataList => _dataList;

    public ScenePassageConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ScenePassageConfig Get(int key) => _dataMap[key];
    public ScenePassageConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

