
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTravelEventConfig
{
    private readonly System.Collections.Generic.Dictionary<int, TravelEventConfig> _dataMap;
    private readonly System.Collections.Generic.List<TravelEventConfig> _dataList;
    
    public TbTravelEventConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TravelEventConfig>();
        _dataList = new System.Collections.Generic.List<TravelEventConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TravelEventConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TravelEventConfig.DeserializeTravelEventConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TravelEventConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TravelEventConfig> DataList => _dataList;

    public TravelEventConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TravelEventConfig Get(int key) => _dataMap[key];
    public TravelEventConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

