
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTreasureConfig
{
    private readonly System.Collections.Generic.Dictionary<int, TreasureConfig> _dataMap;
    private readonly System.Collections.Generic.List<TreasureConfig> _dataList;
    
    public TbTreasureConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TreasureConfig>();
        _dataList = new System.Collections.Generic.List<TreasureConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TreasureConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TreasureConfig.DeserializeTreasureConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TreasureConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TreasureConfig> DataList => _dataList;

    public TreasureConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TreasureConfig Get(int key) => _dataMap[key];
    public TreasureConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

