
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbTravelEventConditionConfig
{
    private readonly System.Collections.Generic.Dictionary<int, TravelEventConditionConfig> _dataMap;
    private readonly System.Collections.Generic.List<TravelEventConditionConfig> _dataList;
    
    public TbTravelEventConditionConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TravelEventConditionConfig>();
        _dataList = new System.Collections.Generic.List<TravelEventConditionConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            TravelEventConditionConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.TravelEventConditionConfig.DeserializeTravelEventConditionConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TravelEventConditionConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<TravelEventConditionConfig> DataList => _dataList;

    public TravelEventConditionConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TravelEventConditionConfig Get(int key) => _dataMap[key];
    public TravelEventConditionConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

