
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbWeatherPoolConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WeatherPoolConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeatherPoolConfig> _dataList;
    
    public TbWeatherPoolConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeatherPoolConfig>();
        _dataList = new System.Collections.Generic.List<WeatherPoolConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeatherPoolConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.WeatherPoolConfig.DeserializeWeatherPoolConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeatherPoolConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WeatherPoolConfig> DataList => _dataList;

    public WeatherPoolConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeatherPoolConfig Get(int key) => _dataMap[key];
    public WeatherPoolConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

