
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbWeatherGroupConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WeatherGroupConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeatherGroupConfig> _dataList;
    
    public TbWeatherGroupConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeatherGroupConfig>();
        _dataList = new System.Collections.Generic.List<WeatherGroupConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeatherGroupConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.WeatherGroupConfig.DeserializeWeatherGroupConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeatherGroupConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WeatherGroupConfig> DataList => _dataList;

    public WeatherGroupConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeatherGroupConfig Get(int key) => _dataMap[key];
    public WeatherGroupConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

