
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbWeatherConfig
{
    private readonly System.Collections.Generic.Dictionary<int, WeatherConfig> _dataMap;
    private readonly System.Collections.Generic.List<WeatherConfig> _dataList;
    
    public TbWeatherConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, WeatherConfig>();
        _dataList = new System.Collections.Generic.List<WeatherConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            WeatherConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.WeatherConfig.DeserializeWeatherConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, WeatherConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<WeatherConfig> DataList => _dataList;

    public WeatherConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public WeatherConfig Get(int key) => _dataMap[key];
    public WeatherConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

