
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbZoneConfig
{
    private readonly System.Collections.Generic.Dictionary<int, ZoneConfig> _dataMap;
    private readonly System.Collections.Generic.List<ZoneConfig> _dataList;
    
    public TbZoneConfig(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, ZoneConfig>();
        _dataList = new System.Collections.Generic.List<ZoneConfig>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            ZoneConfig _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.ZoneConfig.DeserializeZoneConfig(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.ID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, ZoneConfig> DataMap => _dataMap;
    public System.Collections.Generic.List<ZoneConfig> DataList => _dataList;

    public ZoneConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public ZoneConfig Get(int key) => _dataMap[key];
    public ZoneConfig this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

