
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TimeCostConfig : Luban.BeanBase
{
    public TimeCostConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["BehaviourType"].IsString) { throw new SerializationException(); }  BehaviourType = _buf["BehaviourType"]; }
        { if(!_buf["TimeCost"].IsNumber) { throw new SerializationException(); }  TimeCost = _buf["TimeCost"]; }
    }

    public static TimeCostConfig DeserializeTimeCostConfig(JSONNode _buf)
    {
        return new TimeCostConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 行为类型描述
    /// </summary>
    public readonly string BehaviourType;
    /// <summary>
    /// 消耗的时间
    /// </summary>
    public readonly int TimeCost;
   
    public const int __ID__ = 1231351868;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "BehaviourType:" + BehaviourType + ","
        + "TimeCost:" + TimeCost + ","
        + "}";
    }
}

}

