
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TimePeriod : Luban.BeanBase
{
    public TimePeriod(JSONNode _buf) 
    {
        { if(!_buf["Type"].IsNumber) { throw new SerializationException(); }  Type = _buf["Type"]; }
        { if(!_buf["Probability"].IsNumber) { throw new SerializationException(); }  Probability = _buf["Probability"]; }
    }

    public static TimePeriod DeserializeTimePeriod(JSONNode _buf)
    {
        return new TimePeriod(_buf);
    }

    /// <summary>
    /// 类型
    /// </summary>
    public readonly int Type;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly float Probability;
   
    public const int __ID__ = -1607957746;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Type:" + Type + ","
        + "Probability:" + Probability + ","
        + "}";
    }
}

}

