
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TimeConfig : Luban.BeanBase
{
    public TimeConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsString) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Year"].IsNumber) { throw new SerializationException(); }  Year = _buf["Year"]; }
        { if(!_buf["Month"].IsNumber) { throw new SerializationException(); }  Month = _buf["Month"]; }
        { if(!_buf["Day"].IsNumber) { throw new SerializationException(); }  Day = _buf["Day"]; }
        { if(!_buf["ShowText"].IsString) { throw new SerializationException(); }  ShowText = _buf["ShowText"]; }
        { if(!_buf["OtherText"].IsString) { throw new SerializationException(); }  OtherText = _buf["OtherText"]; }
        { if(!_buf["Season"].IsNumber) { throw new SerializationException(); }  Season = _buf["Season"]; }
        { if(!_buf["DateTag"].IsString) { throw new SerializationException(); }  DateTag = _buf["DateTag"]; }
    }

    public static TimeConfig DeserializeTimeConfig(JSONNode _buf)
    {
        return new TimeConfig(_buf);
    }

    /// <summary>
    /// 联合主键
    /// </summary>
    public readonly string ID;
    /// <summary>
    /// 年
    /// </summary>
    public readonly int Year;
    /// <summary>
    /// 月
    /// </summary>
    public readonly int Month;
    /// <summary>
    /// 日
    /// </summary>
    public readonly int Day;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string ShowText;
    /// <summary>
    /// 其余显示（农历记日）
    /// </summary>
    public readonly string OtherText;
    /// <summary>
    /// 季候
    /// </summary>
    public readonly int Season;
    /// <summary>
    /// 日期类型标签
    /// </summary>
    public readonly string DateTag;
   
    public const int __ID__ = -1971023729;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Year:" + Year + ","
        + "Month:" + Month + ","
        + "Day:" + Day + ","
        + "ShowText:" + ShowText + ","
        + "OtherText:" + OtherText + ","
        + "Season:" + Season + ","
        + "DateTag:" + DateTag + ","
        + "}";
    }
}

}

