
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TravelEventConditionConfig : Luban.BeanBase
{
    public TravelEventConditionConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["EventID"].IsNumber) { throw new SerializationException(); }  EventID = _buf["EventID"]; }
        { if(!_buf["ConditionID"].IsNumber) { throw new SerializationException(); }  ConditionID = _buf["ConditionID"]; }
        { var __json0 = _buf["ConditionParam"]; if(!__json0.IsArray) { throw new SerializationException(); } ConditionParam = new System.Collections.Generic.List<float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { float __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  ConditionParam.Add(__v0); }   }
    }

    public static TravelEventConditionConfig DeserializeTravelEventConditionConfig(JSONNode _buf)
    {
        return new TravelEventConditionConfig(_buf);
    }

    /// <summary>
    /// 条件ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 事件ID
    /// </summary>
    public readonly int EventID;
    /// <summary>
    /// 条件ID
    /// </summary>
    public readonly int ConditionID;
    /// <summary>
    /// 条件参数
    /// </summary>
    public readonly System.Collections.Generic.List<float> ConditionParam;
   
    public const int __ID__ = -167864163;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "EventID:" + EventID + ","
        + "ConditionID:" + ConditionID + ","
        + "ConditionParam:" + Luban.StringUtil.CollectionToString(ConditionParam) + ","
        + "}";
    }
}

}

