
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class TravelEventConfig : Luban.BeanBase
{
    public TravelEventConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["RepeatTrigger"].IsNumber) { throw new SerializationException(); }  RepeatTrigger = _buf["RepeatTrigger"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
    }

    public static TravelEventConfig DeserializeTravelEventConfig(JSONNode _buf)
    {
        return new TravelEventConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 是否重复触发
    /// </summary>
    public readonly int RepeatTrigger;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
   
    public const int __ID__ = -1175856414;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "RepeatTrigger:" + RepeatTrigger + ","
        + "Weight:" + Weight + ","
        + "}";
    }
}

}

