
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum TreasureFeature
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 金刚伞
        /// </summary>
        JinGangSan = 1,
        /// <summary>
        /// 渡梦舟
        /// </summary>
        DuMengZhou = 2,
    }

} 

