
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeatherGroupConfig : Luban.BeanBase
{
    public WeatherGroupConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Default"].IsNumber) { throw new SerializationException(); }  Default = _buf["Default"]; }
        { var __json0 = _buf["WeatherPool"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; WeatherPool = new WeatherPoolInGroupData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { WeatherPoolInGroupData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.WeatherPoolInGroupData.DeserializeWeatherPoolInGroupData(__e0);  }  WeatherPool[__index0++] = __v0; }   }
    }

    public static WeatherGroupConfig DeserializeWeatherGroupConfig(JSONNode _buf)
    {
        return new WeatherGroupConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 默认天气
    /// </summary>
    public readonly int Default;
    /// <summary>
    /// 气候天气池（季候,天气池）
    /// </summary>
    public readonly WeatherPoolInGroupData[] WeatherPool;
   
    public const int __ID__ = -1907968467;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in WeatherPool) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Default:" + Default + ","
        + "WeatherPool:" + Luban.StringUtil.CollectionToString(WeatherPool) + ","
        + "}";
    }
}

}

