
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg
{ 
    public enum WeatherType
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 晴
        /// </summary>
        Sunny = 1,
        /// <summary>
        /// 阴
        /// </summary>
        Shade = 2,
        /// <summary>
        /// 雨
        /// </summary>
        Rain = 3,
        /// <summary>
        /// 雾
        /// </summary>
        Fog = 4,
    }

} 

