
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeatherConfig : Luban.BeanBase
{
    public WeatherConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["Des"].IsString) { throw new SerializationException(); }  Des = _buf["Des"]; }
        { if(!_buf["WeatherType"].IsNumber) { throw new SerializationException(); }  WeatherType = _buf["WeatherType"]; }
        { if(!_buf["Filter"].IsNumber) { throw new SerializationException(); }  Filter = _buf["Filter"]; }
    }

    public static WeatherConfig DeserializeWeatherConfig(JSONNode _buf)
    {
        return new WeatherConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 天气描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 天气类型
    /// </summary>
    public readonly int WeatherType;
    /// <summary>
    /// 滤镜
    /// </summary>
    public readonly int Filter;
   
    public const int __ID__ = 1918570550;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "Des:" + Des + ","
        + "WeatherType:" + WeatherType + ","
        + "Filter:" + Filter + ","
        + "}";
    }
}

}

