
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeatherPoolInGroupData : Luban.BeanBase
{
    public WeatherPoolInGroupData(JSONNode _buf) 
    {
        { if(!_buf["SeasonID"].IsNumber) { throw new SerializationException(); }  SeasonID = _buf["SeasonID"]; }
        { if(!_buf["WeatherPoolID"].IsNumber) { throw new SerializationException(); }  WeatherPoolID = _buf["WeatherPoolID"]; }
    }

    public static WeatherPoolInGroupData DeserializeWeatherPoolInGroupData(JSONNode _buf)
    {
        return new WeatherPoolInGroupData(_buf);
    }

    /// <summary>
    /// 季候ID
    /// </summary>
    public readonly int SeasonID;
    /// <summary>
    /// 天气池ID
    /// </summary>
    public readonly int WeatherPoolID;
   
    public const int __ID__ = -2622732;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "SeasonID:" + SeasonID + ","
        + "WeatherPoolID:" + WeatherPoolID + ","
        + "}";
    }
}

}

