
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeatherPoolConfig : Luban.BeanBase
{
    public WeatherPoolConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { var __json0 = _buf["WeatherPoolData"]; if(!__json0.IsArray) { throw new SerializationException(); } int _n0 = __json0.Count; WeatherPoolData = new WeatherPoolData[_n0]; int __index0=0; foreach(JSONNode __e0 in __json0.Children) { WeatherPoolData __v0;  { if(!__e0.IsObject) { throw new SerializationException(); }  __v0 = global::cfg.WeatherPoolData.DeserializeWeatherPoolData(__e0);  }  WeatherPoolData[__index0++] = __v0; }   }
    }

    public static WeatherPoolConfig DeserializeWeatherPoolConfig(JSONNode _buf)
    {
        return new WeatherPoolConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 天气池数据
    /// </summary>
    public readonly WeatherPoolData[] WeatherPoolData;
   
    public const int __ID__ = 2115597682;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        foreach (var _e in WeatherPoolData) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "WeatherPoolData:" + Luban.StringUtil.CollectionToString(WeatherPoolData) + ","
        + "}";
    }
}

}

