
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class WeatherPoolData : Luban.BeanBase
{
    public WeatherPoolData(JSONNode _buf) 
    {
        { if(!_buf["WeatherID"].IsNumber) { throw new SerializationException(); }  WeatherID = _buf["WeatherID"]; }
        { if(!_buf["Weight"].IsNumber) { throw new SerializationException(); }  Weight = _buf["Weight"]; }
        { if(!_buf["MinContinue"].IsNumber) { throw new SerializationException(); }  MinContinue = _buf["MinContinue"]; }
        { if(!_buf["MaxContinue"].IsNumber) { throw new SerializationException(); }  MaxContinue = _buf["MaxContinue"]; }
    }

    public static WeatherPoolData DeserializeWeatherPoolData(JSONNode _buf)
    {
        return new WeatherPoolData(_buf);
    }

    /// <summary>
    /// 天气类ID
    /// </summary>
    public readonly int WeatherID;
    /// <summary>
    /// 权重
    /// </summary>
    public readonly int Weight;
    /// <summary>
    /// 最小持续时间
    /// </summary>
    public readonly int MinContinue;
    /// <summary>
    /// 最大持续时间
    /// </summary>
    public readonly int MaxContinue;
   
    public const int __ID__ = -1874874918;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "WeatherID:" + WeatherID + ","
        + "Weight:" + Weight + ","
        + "MinContinue:" + MinContinue + ","
        + "MaxContinue:" + MaxContinue + ","
        + "}";
    }
}

}

