
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public sealed partial class ZoneConfig : Luban.BeanBase
{
    public ZoneConfig(JSONNode _buf) 
    {
        { if(!_buf["ID"].IsNumber) { throw new SerializationException(); }  ID = _buf["ID"]; }
        { if(!_buf["ZoneName"].IsString) { throw new SerializationException(); }  ZoneName = _buf["ZoneName"]; }
        { if(!_buf["EntrySceneID"].IsNumber) { throw new SerializationException(); }  EntrySceneID = _buf["EntrySceneID"]; }
        { if(!_buf["WeatherGroupID"].IsNumber) { throw new SerializationException(); }  WeatherGroupID = _buf["WeatherGroupID"]; }
        { if(!_buf["MapID"].IsNumber) { throw new SerializationException(); }  MapID = _buf["MapID"]; }
        { if(!_buf["Position"].IsObject) { throw new SerializationException(); }  Position = global::cfg.Position.DeserializePosition(_buf["Position"]);  }
        { if(!_buf["Travel"].IsNumber) { throw new SerializationException(); }  Travel = _buf["Travel"]; }
        { if(!_buf["IconResource"].IsString) { throw new SerializationException(); }  IconResource = _buf["IconResource"]; }
    }

    public static ZoneConfig DeserializeZoneConfig(JSONNode _buf)
    {
        return new ZoneConfig(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int ID;
    /// <summary>
    /// 地区名
    /// </summary>
    public readonly string ZoneName;
    /// <summary>
    /// 入口场景
    /// </summary>
    public readonly int EntrySceneID;
    /// <summary>
    /// 天气组ID
    /// </summary>
    public readonly int WeatherGroupID;
    /// <summary>
    /// 归属地图ID
    /// </summary>
    public readonly int MapID;
    /// <summary>
    /// 小地图显示位置
    /// </summary>
    public readonly Position Position;
    /// <summary>
    /// 旅行开关
    /// </summary>
    public readonly int Travel;
    /// <summary>
    /// 地图显示美术资源
    /// </summary>
    public readonly string IconResource;
   
    public const int __ID__ = 632880686;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Position?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "ID:" + ID + ","
        + "ZoneName:" + ZoneName + ","
        + "EntrySceneID:" + EntrySceneID + ","
        + "WeatherGroupID:" + WeatherGroupID + ","
        + "MapID:" + MapID + ","
        + "Position:" + Position + ","
        + "Travel:" + Travel + ","
        + "IconResource:" + IconResource + ","
        + "}";
    }
}

}

