
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbBattleSkill
{
    private readonly System.Collections.Generic.Dictionary<int, BattleSkill> _dataMap;
    private readonly System.Collections.Generic.List<BattleSkill> _dataList;
    
    public TbBattleSkill(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, BattleSkill>();
        _dataList = new System.Collections.Generic.List<BattleSkill>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            BattleSkill _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.BattleSkill.DeserializeBattleSkill(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, BattleSkill> DataMap => _dataMap;
    public System.Collections.Generic.List<BattleSkill> DataList => _dataList;

    public BattleSkill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public BattleSkill Get(int key) => _dataMap[key];
    public BattleSkill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

