
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg
{
public partial class TbHeartMethod
{
    private readonly System.Collections.Generic.Dictionary<int, HeartMethod> _dataMap;
    private readonly System.Collections.Generic.List<HeartMethod> _dataList;
    
    public TbHeartMethod(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, HeartMethod>();
        _dataList = new System.Collections.Generic.List<HeartMethod>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            HeartMethod _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.HeartMethod.DeserializeHeartMethod(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, HeartMethod> DataMap => _dataMap;
    public System.Collections.Generic.List<HeartMethod> DataList => _dataList;

    public HeartMethod GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public HeartMethod Get(int key) => _dataMap[key];
    public HeartMethod this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

